// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant_document/merchant_document_query.proto

package merchant_document

import (
	common "github.com/MamangRust/monolith-payment-gateway-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponsePaginationMerchantDocument struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*MerchantDocument    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDocument) Reset() {
	*x = ApiResponsePaginationMerchantDocument{}
	mi := &file_merchant_document_merchant_document_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDocument) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDocument) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_merchant_document_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDocument.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDocument) Descriptor() ([]byte, []int) {
	return file_merchant_document_merchant_document_query_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponsePaginationMerchantDocument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocument) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocument) GetData() []*MerchantDocument {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDocument) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type ApiResponsePaginationMerchantDocumentAt struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Status         string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*MerchantDocumentDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta      `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDocumentAt) Reset() {
	*x = ApiResponsePaginationMerchantDocumentAt{}
	mi := &file_merchant_document_merchant_document_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDocumentAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDocumentAt) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDocumentAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_document_merchant_document_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDocumentAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDocumentAt) Descriptor() ([]byte, []int) {
	return file_merchant_document_merchant_document_query_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetData() []*MerchantDocumentDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDocumentAt) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

var File_merchant_document_merchant_document_query_proto protoreflect.FileDescriptor

const file_merchant_document_merchant_document_query_proto_rawDesc = "" +
	"\n" +
	"/merchant_document/merchant_document_query.proto\x12\x14pb.merchant_document\x1a)merchant_document/merchant_document.proto\x1a\x10common/api.proto\"\xd8\x01\n" +
	"%ApiResponsePaginationMerchantDocument\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x04data\x18\x03 \x03(\v2&.pb.merchant_document.MerchantDocumentR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta\"\xe2\x01\n" +
	"'ApiResponsePaginationMerchantDocumentAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x04data\x18\x03 \x03(\v2..pb.merchant_document.MerchantDocumentDeleteAtR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta2\xac\x04\n" +
	"\x1cMerchantDocumentQueryService\x12\x7f\n" +
	"\aFindAll\x125.pb.merchant_document.FindAllMerchantDocumentsRequest\x1a;.pb.merchant_document.ApiResponsePaginationMerchantDocument\"\x00\x12\x87\x01\n" +
	"\rFindAllActive\x125.pb.merchant_document.FindAllMerchantDocumentsRequest\x1a=.pb.merchant_document.ApiResponsePaginationMerchantDocumentAt\"\x00\x12\x88\x01\n" +
	"\x0eFindAllTrashed\x125.pb.merchant_document.FindAllMerchantDocumentsRequest\x1a=.pb.merchant_document.ApiResponsePaginationMerchantDocumentAt\"\x00\x12v\n" +
	"\bFindById\x125.pb.merchant_document.FindMerchantDocumentByIdRequest\x1a1.pb.merchant_document.ApiResponseMerchantDocument\"\x00BEZCgithub.com/MamangRust/monolith-payment-gateway-pb/merchant_documentb\x06proto3"

var (
	file_merchant_document_merchant_document_query_proto_rawDescOnce sync.Once
	file_merchant_document_merchant_document_query_proto_rawDescData []byte
)

func file_merchant_document_merchant_document_query_proto_rawDescGZIP() []byte {
	file_merchant_document_merchant_document_query_proto_rawDescOnce.Do(func() {
		file_merchant_document_merchant_document_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_document_merchant_document_query_proto_rawDesc), len(file_merchant_document_merchant_document_query_proto_rawDesc)))
	})
	return file_merchant_document_merchant_document_query_proto_rawDescData
}

var file_merchant_document_merchant_document_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_merchant_document_merchant_document_query_proto_goTypes = []any{
	(*ApiResponsePaginationMerchantDocument)(nil),   // 0: pb.merchant_document.ApiResponsePaginationMerchantDocument
	(*ApiResponsePaginationMerchantDocumentAt)(nil), // 1: pb.merchant_document.ApiResponsePaginationMerchantDocumentAt
	(*MerchantDocument)(nil),                        // 2: pb.merchant_document.MerchantDocument
	(*common.PaginationMeta)(nil),                   // 3: pb.common.PaginationMeta
	(*MerchantDocumentDeleteAt)(nil),                // 4: pb.merchant_document.MerchantDocumentDeleteAt
	(*FindAllMerchantDocumentsRequest)(nil),         // 5: pb.merchant_document.FindAllMerchantDocumentsRequest
	(*FindMerchantDocumentByIdRequest)(nil),         // 6: pb.merchant_document.FindMerchantDocumentByIdRequest
	(*ApiResponseMerchantDocument)(nil),             // 7: pb.merchant_document.ApiResponseMerchantDocument
}
var file_merchant_document_merchant_document_query_proto_depIdxs = []int32{
	2, // 0: pb.merchant_document.ApiResponsePaginationMerchantDocument.data:type_name -> pb.merchant_document.MerchantDocument
	3, // 1: pb.merchant_document.ApiResponsePaginationMerchantDocument.paginationMeta:type_name -> pb.common.PaginationMeta
	4, // 2: pb.merchant_document.ApiResponsePaginationMerchantDocumentAt.data:type_name -> pb.merchant_document.MerchantDocumentDeleteAt
	3, // 3: pb.merchant_document.ApiResponsePaginationMerchantDocumentAt.paginationMeta:type_name -> pb.common.PaginationMeta
	5, // 4: pb.merchant_document.MerchantDocumentQueryService.FindAll:input_type -> pb.merchant_document.FindAllMerchantDocumentsRequest
	5, // 5: pb.merchant_document.MerchantDocumentQueryService.FindAllActive:input_type -> pb.merchant_document.FindAllMerchantDocumentsRequest
	5, // 6: pb.merchant_document.MerchantDocumentQueryService.FindAllTrashed:input_type -> pb.merchant_document.FindAllMerchantDocumentsRequest
	6, // 7: pb.merchant_document.MerchantDocumentQueryService.FindById:input_type -> pb.merchant_document.FindMerchantDocumentByIdRequest
	0, // 8: pb.merchant_document.MerchantDocumentQueryService.FindAll:output_type -> pb.merchant_document.ApiResponsePaginationMerchantDocument
	1, // 9: pb.merchant_document.MerchantDocumentQueryService.FindAllActive:output_type -> pb.merchant_document.ApiResponsePaginationMerchantDocumentAt
	1, // 10: pb.merchant_document.MerchantDocumentQueryService.FindAllTrashed:output_type -> pb.merchant_document.ApiResponsePaginationMerchantDocumentAt
	7, // 11: pb.merchant_document.MerchantDocumentQueryService.FindById:output_type -> pb.merchant_document.ApiResponseMerchantDocument
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_merchant_document_merchant_document_query_proto_init() }
func file_merchant_document_merchant_document_query_proto_init() {
	if File_merchant_document_merchant_document_query_proto != nil {
		return
	}
	file_merchant_document_merchant_document_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_document_merchant_document_query_proto_rawDesc), len(file_merchant_document_merchant_document_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_document_merchant_document_query_proto_goTypes,
		DependencyIndexes: file_merchant_document_merchant_document_query_proto_depIdxs,
		MessageInfos:      file_merchant_document_merchant_document_query_proto_msgTypes,
	}.Build()
	File_merchant_document_merchant_document_query_proto = out.File
	file_merchant_document_merchant_document_query_proto_goTypes = nil
	file_merchant_document_merchant_document_query_proto_depIdxs = nil
}
