// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant/stats/merchant_stats_totalamount.proto

package stats

import (
	merchant "github.com/MamangRust/monolith-payment-gateway-pb/merchant"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantResponseMonthlyTotalAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Year          string                 `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponseMonthlyTotalAmount) Reset() {
	*x = MerchantResponseMonthlyTotalAmount{}
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponseMonthlyTotalAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponseMonthlyTotalAmount) ProtoMessage() {}

func (x *MerchantResponseMonthlyTotalAmount) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponseMonthlyTotalAmount.ProtoReflect.Descriptor instead.
func (*MerchantResponseMonthlyTotalAmount) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_totalamount_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantResponseMonthlyTotalAmount) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MerchantResponseMonthlyTotalAmount) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *MerchantResponseMonthlyTotalAmount) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type MerchantResponseYearlyTotalAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponseYearlyTotalAmount) Reset() {
	*x = MerchantResponseYearlyTotalAmount{}
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponseYearlyTotalAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponseYearlyTotalAmount) ProtoMessage() {}

func (x *MerchantResponseYearlyTotalAmount) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponseYearlyTotalAmount.ProtoReflect.Descriptor instead.
func (*MerchantResponseYearlyTotalAmount) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_totalamount_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantResponseYearlyTotalAmount) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *MerchantResponseYearlyTotalAmount) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseMerchantMonthlyTotalAmount struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Status        string                                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantResponseMonthlyTotalAmount `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantMonthlyTotalAmount) Reset() {
	*x = ApiResponseMerchantMonthlyTotalAmount{}
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantMonthlyTotalAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantMonthlyTotalAmount) ProtoMessage() {}

func (x *ApiResponseMerchantMonthlyTotalAmount) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantMonthlyTotalAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantMonthlyTotalAmount) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_totalamount_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseMerchantMonthlyTotalAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantMonthlyTotalAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantMonthlyTotalAmount) GetData() []*MerchantResponseMonthlyTotalAmount {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseMerchantYearlyTotalAmount struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Status        string                               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantResponseYearlyTotalAmount `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantYearlyTotalAmount) Reset() {
	*x = ApiResponseMerchantYearlyTotalAmount{}
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantYearlyTotalAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantYearlyTotalAmount) ProtoMessage() {}

func (x *ApiResponseMerchantYearlyTotalAmount) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_totalamount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantYearlyTotalAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantYearlyTotalAmount) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_totalamount_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseMerchantYearlyTotalAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantYearlyTotalAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantYearlyTotalAmount) GetData() []*MerchantResponseYearlyTotalAmount {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_merchant_stats_merchant_stats_totalamount_proto protoreflect.FileDescriptor

const file_merchant_stats_merchant_stats_totalamount_proto_rawDesc = "" +
	"\n" +
	"/merchant/stats/merchant_stats_totalamount.proto\x12\x11pb.merchant.stats\x1a\x17merchant/merchant.proto\"q\n" +
	"\"MerchantResponseMonthlyTotalAmount\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x12\n" +
	"\x04year\x18\x02 \x01(\tR\x04year\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\"Z\n" +
	"!MerchantResponseYearlyTotalAmount\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\"\xa4\x01\n" +
	"%ApiResponseMerchantMonthlyTotalAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12I\n" +
	"\x04data\x18\x03 \x03(\v25.pb.merchant.stats.MerchantResponseMonthlyTotalAmountR\x04data\"\xa2\x01\n" +
	"$ApiResponseMerchantYearlyTotalAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\x04data\x18\x03 \x03(\v24.pb.merchant.stats.MerchantResponseYearlyTotalAmountR\x04data2\xab\x06\n" +
	"\x1fMerchantStatsTotalAmountService\x12{\n" +
	"\x1eFindMonthlyTotalAmountMerchant\x12\x1d.pb.merchant.FindYearMerchant\x1a8.pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount\"\x00\x12y\n" +
	"\x1dFindYearlyTotalAmountMerchant\x12\x1d.pb.merchant.FindYearMerchant\x1a7.pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount\"\x00\x12\x82\x01\n" +
	"!FindMonthlyTotalAmountByMerchants\x12!.pb.merchant.FindYearMerchantById\x1a8.pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount\"\x00\x12\x80\x01\n" +
	" FindYearlyTotalAmountByMerchants\x12!.pb.merchant.FindYearMerchantById\x1a7.pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount\"\x00\x12\x83\x01\n" +
	"\x1eFindMonthlyTotalAmountByApikey\x12%.pb.merchant.FindYearMerchantByApikey\x1a8.pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount\"\x00\x12\x81\x01\n" +
	"\x1dFindYearlyTotalAmountByApikey\x12%.pb.merchant.FindYearMerchantByApikey\x1a7.pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount\"\x00BBZ@github.com/MamangRust/monolith-payment-gateway-pb/merchant/statsb\x06proto3"

var (
	file_merchant_stats_merchant_stats_totalamount_proto_rawDescOnce sync.Once
	file_merchant_stats_merchant_stats_totalamount_proto_rawDescData []byte
)

func file_merchant_stats_merchant_stats_totalamount_proto_rawDescGZIP() []byte {
	file_merchant_stats_merchant_stats_totalamount_proto_rawDescOnce.Do(func() {
		file_merchant_stats_merchant_stats_totalamount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_stats_merchant_stats_totalamount_proto_rawDesc), len(file_merchant_stats_merchant_stats_totalamount_proto_rawDesc)))
	})
	return file_merchant_stats_merchant_stats_totalamount_proto_rawDescData
}

var file_merchant_stats_merchant_stats_totalamount_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_merchant_stats_merchant_stats_totalamount_proto_goTypes = []any{
	(*MerchantResponseMonthlyTotalAmount)(nil),    // 0: pb.merchant.stats.MerchantResponseMonthlyTotalAmount
	(*MerchantResponseYearlyTotalAmount)(nil),     // 1: pb.merchant.stats.MerchantResponseYearlyTotalAmount
	(*ApiResponseMerchantMonthlyTotalAmount)(nil), // 2: pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount
	(*ApiResponseMerchantYearlyTotalAmount)(nil),  // 3: pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount
	(*merchant.FindYearMerchant)(nil),             // 4: pb.merchant.FindYearMerchant
	(*merchant.FindYearMerchantById)(nil),         // 5: pb.merchant.FindYearMerchantById
	(*merchant.FindYearMerchantByApikey)(nil),     // 6: pb.merchant.FindYearMerchantByApikey
}
var file_merchant_stats_merchant_stats_totalamount_proto_depIdxs = []int32{
	0, // 0: pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount.data:type_name -> pb.merchant.stats.MerchantResponseMonthlyTotalAmount
	1, // 1: pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount.data:type_name -> pb.merchant.stats.MerchantResponseYearlyTotalAmount
	4, // 2: pb.merchant.stats.MerchantStatsTotalAmountService.FindMonthlyTotalAmountMerchant:input_type -> pb.merchant.FindYearMerchant
	4, // 3: pb.merchant.stats.MerchantStatsTotalAmountService.FindYearlyTotalAmountMerchant:input_type -> pb.merchant.FindYearMerchant
	5, // 4: pb.merchant.stats.MerchantStatsTotalAmountService.FindMonthlyTotalAmountByMerchants:input_type -> pb.merchant.FindYearMerchantById
	5, // 5: pb.merchant.stats.MerchantStatsTotalAmountService.FindYearlyTotalAmountByMerchants:input_type -> pb.merchant.FindYearMerchantById
	6, // 6: pb.merchant.stats.MerchantStatsTotalAmountService.FindMonthlyTotalAmountByApikey:input_type -> pb.merchant.FindYearMerchantByApikey
	6, // 7: pb.merchant.stats.MerchantStatsTotalAmountService.FindYearlyTotalAmountByApikey:input_type -> pb.merchant.FindYearMerchantByApikey
	2, // 8: pb.merchant.stats.MerchantStatsTotalAmountService.FindMonthlyTotalAmountMerchant:output_type -> pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount
	3, // 9: pb.merchant.stats.MerchantStatsTotalAmountService.FindYearlyTotalAmountMerchant:output_type -> pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount
	2, // 10: pb.merchant.stats.MerchantStatsTotalAmountService.FindMonthlyTotalAmountByMerchants:output_type -> pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount
	3, // 11: pb.merchant.stats.MerchantStatsTotalAmountService.FindYearlyTotalAmountByMerchants:output_type -> pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount
	2, // 12: pb.merchant.stats.MerchantStatsTotalAmountService.FindMonthlyTotalAmountByApikey:output_type -> pb.merchant.stats.ApiResponseMerchantMonthlyTotalAmount
	3, // 13: pb.merchant.stats.MerchantStatsTotalAmountService.FindYearlyTotalAmountByApikey:output_type -> pb.merchant.stats.ApiResponseMerchantYearlyTotalAmount
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_merchant_stats_merchant_stats_totalamount_proto_init() }
func file_merchant_stats_merchant_stats_totalamount_proto_init() {
	if File_merchant_stats_merchant_stats_totalamount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_stats_merchant_stats_totalamount_proto_rawDesc), len(file_merchant_stats_merchant_stats_totalamount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_stats_merchant_stats_totalamount_proto_goTypes,
		DependencyIndexes: file_merchant_stats_merchant_stats_totalamount_proto_depIdxs,
		MessageInfos:      file_merchant_stats_merchant_stats_totalamount_proto_msgTypes,
	}.Build()
	File_merchant_stats_merchant_stats_totalamount_proto = out.File
	file_merchant_stats_merchant_stats_totalamount_proto_goTypes = nil
	file_merchant_stats_merchant_stats_totalamount_proto_depIdxs = nil
}
