// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant/stats/merchant_stats_method.proto

package stats

import (
	merchant "github.com/MamangRust/monolith-payment-gateway-pb/merchant"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantResponseMonthlyPaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponseMonthlyPaymentMethod) Reset() {
	*x = MerchantResponseMonthlyPaymentMethod{}
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponseMonthlyPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponseMonthlyPaymentMethod) ProtoMessage() {}

func (x *MerchantResponseMonthlyPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponseMonthlyPaymentMethod.ProtoReflect.Descriptor instead.
func (*MerchantResponseMonthlyPaymentMethod) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_method_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantResponseMonthlyPaymentMethod) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MerchantResponseMonthlyPaymentMethod) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *MerchantResponseMonthlyPaymentMethod) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type MerchantResponseYearlyPaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponseYearlyPaymentMethod) Reset() {
	*x = MerchantResponseYearlyPaymentMethod{}
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponseYearlyPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponseYearlyPaymentMethod) ProtoMessage() {}

func (x *MerchantResponseYearlyPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponseYearlyPaymentMethod.ProtoReflect.Descriptor instead.
func (*MerchantResponseYearlyPaymentMethod) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_method_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantResponseYearlyPaymentMethod) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *MerchantResponseYearlyPaymentMethod) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *MerchantResponseYearlyPaymentMethod) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseMerchantMonthlyPaymentMethod struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Status        string                                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantResponseMonthlyPaymentMethod `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantMonthlyPaymentMethod) Reset() {
	*x = ApiResponseMerchantMonthlyPaymentMethod{}
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantMonthlyPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantMonthlyPaymentMethod) ProtoMessage() {}

func (x *ApiResponseMerchantMonthlyPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantMonthlyPaymentMethod.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantMonthlyPaymentMethod) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_method_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseMerchantMonthlyPaymentMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantMonthlyPaymentMethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantMonthlyPaymentMethod) GetData() []*MerchantResponseMonthlyPaymentMethod {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseMerchantYearlyPaymentMethod struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Status        string                                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantResponseYearlyPaymentMethod `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantYearlyPaymentMethod) Reset() {
	*x = ApiResponseMerchantYearlyPaymentMethod{}
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantYearlyPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantYearlyPaymentMethod) ProtoMessage() {}

func (x *ApiResponseMerchantYearlyPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_stats_merchant_stats_method_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantYearlyPaymentMethod.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantYearlyPaymentMethod) Descriptor() ([]byte, []int) {
	return file_merchant_stats_merchant_stats_method_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseMerchantYearlyPaymentMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantYearlyPaymentMethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantYearlyPaymentMethod) GetData() []*MerchantResponseYearlyPaymentMethod {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_merchant_stats_merchant_stats_method_proto protoreflect.FileDescriptor

const file_merchant_stats_merchant_stats_method_proto_rawDesc = "" +
	"\n" +
	"*merchant/stats/merchant_stats_method.proto\x12\x11pb.merchant.stats\x1a\x17merchant/merchant.proto\"\x86\x01\n" +
	"$MerchantResponseMonthlyPaymentMethod\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\"\x83\x01\n" +
	"#MerchantResponseYearlyPaymentMethod\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\"\xa8\x01\n" +
	"'ApiResponseMerchantMonthlyPaymentMethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12K\n" +
	"\x04data\x18\x03 \x03(\v27.pb.merchant.stats.MerchantResponseMonthlyPaymentMethodR\x04data\"\xa6\x01\n" +
	"&ApiResponseMerchantYearlyPaymentMethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12J\n" +
	"\x04data\x18\x03 \x03(\v26.pb.merchant.stats.MerchantResponseYearlyPaymentMethodR\x04data2\xc0\x06\n" +
	"\x1aMerchantStatsMethodService\x12\x80\x01\n" +
	"!FindMonthlyPaymentMethodsMerchant\x12\x1d.pb.merchant.FindYearMerchant\x1a:.pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod\"\x00\x12}\n" +
	"\x1fFindYearlyPaymentMethodMerchant\x12\x1d.pb.merchant.FindYearMerchant\x1a9.pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod\"\x00\x12\x86\x01\n" +
	"#FindMonthlyPaymentMethodByMerchants\x12!.pb.merchant.FindYearMerchantById\x1a:.pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod\"\x00\x12\x84\x01\n" +
	"\"FindYearlyPaymentMethodByMerchants\x12!.pb.merchant.FindYearMerchantById\x1a9.pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod\"\x00\x12\x87\x01\n" +
	" FindMonthlyPaymentMethodByApikey\x12%.pb.merchant.FindYearMerchantByApikey\x1a:.pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod\"\x00\x12\x85\x01\n" +
	"\x1fFindYearlyPaymentMethodByApikey\x12%.pb.merchant.FindYearMerchantByApikey\x1a9.pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod\"\x00BBZ@github.com/MamangRust/monolith-payment-gateway-pb/merchant/statsb\x06proto3"

var (
	file_merchant_stats_merchant_stats_method_proto_rawDescOnce sync.Once
	file_merchant_stats_merchant_stats_method_proto_rawDescData []byte
)

func file_merchant_stats_merchant_stats_method_proto_rawDescGZIP() []byte {
	file_merchant_stats_merchant_stats_method_proto_rawDescOnce.Do(func() {
		file_merchant_stats_merchant_stats_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_stats_merchant_stats_method_proto_rawDesc), len(file_merchant_stats_merchant_stats_method_proto_rawDesc)))
	})
	return file_merchant_stats_merchant_stats_method_proto_rawDescData
}

var file_merchant_stats_merchant_stats_method_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_merchant_stats_merchant_stats_method_proto_goTypes = []any{
	(*MerchantResponseMonthlyPaymentMethod)(nil),    // 0: pb.merchant.stats.MerchantResponseMonthlyPaymentMethod
	(*MerchantResponseYearlyPaymentMethod)(nil),     // 1: pb.merchant.stats.MerchantResponseYearlyPaymentMethod
	(*ApiResponseMerchantMonthlyPaymentMethod)(nil), // 2: pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod
	(*ApiResponseMerchantYearlyPaymentMethod)(nil),  // 3: pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod
	(*merchant.FindYearMerchant)(nil),               // 4: pb.merchant.FindYearMerchant
	(*merchant.FindYearMerchantById)(nil),           // 5: pb.merchant.FindYearMerchantById
	(*merchant.FindYearMerchantByApikey)(nil),       // 6: pb.merchant.FindYearMerchantByApikey
}
var file_merchant_stats_merchant_stats_method_proto_depIdxs = []int32{
	0, // 0: pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod.data:type_name -> pb.merchant.stats.MerchantResponseMonthlyPaymentMethod
	1, // 1: pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod.data:type_name -> pb.merchant.stats.MerchantResponseYearlyPaymentMethod
	4, // 2: pb.merchant.stats.MerchantStatsMethodService.FindMonthlyPaymentMethodsMerchant:input_type -> pb.merchant.FindYearMerchant
	4, // 3: pb.merchant.stats.MerchantStatsMethodService.FindYearlyPaymentMethodMerchant:input_type -> pb.merchant.FindYearMerchant
	5, // 4: pb.merchant.stats.MerchantStatsMethodService.FindMonthlyPaymentMethodByMerchants:input_type -> pb.merchant.FindYearMerchantById
	5, // 5: pb.merchant.stats.MerchantStatsMethodService.FindYearlyPaymentMethodByMerchants:input_type -> pb.merchant.FindYearMerchantById
	6, // 6: pb.merchant.stats.MerchantStatsMethodService.FindMonthlyPaymentMethodByApikey:input_type -> pb.merchant.FindYearMerchantByApikey
	6, // 7: pb.merchant.stats.MerchantStatsMethodService.FindYearlyPaymentMethodByApikey:input_type -> pb.merchant.FindYearMerchantByApikey
	2, // 8: pb.merchant.stats.MerchantStatsMethodService.FindMonthlyPaymentMethodsMerchant:output_type -> pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod
	3, // 9: pb.merchant.stats.MerchantStatsMethodService.FindYearlyPaymentMethodMerchant:output_type -> pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod
	2, // 10: pb.merchant.stats.MerchantStatsMethodService.FindMonthlyPaymentMethodByMerchants:output_type -> pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod
	3, // 11: pb.merchant.stats.MerchantStatsMethodService.FindYearlyPaymentMethodByMerchants:output_type -> pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod
	2, // 12: pb.merchant.stats.MerchantStatsMethodService.FindMonthlyPaymentMethodByApikey:output_type -> pb.merchant.stats.ApiResponseMerchantMonthlyPaymentMethod
	3, // 13: pb.merchant.stats.MerchantStatsMethodService.FindYearlyPaymentMethodByApikey:output_type -> pb.merchant.stats.ApiResponseMerchantYearlyPaymentMethod
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_merchant_stats_merchant_stats_method_proto_init() }
func file_merchant_stats_merchant_stats_method_proto_init() {
	if File_merchant_stats_merchant_stats_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_stats_merchant_stats_method_proto_rawDesc), len(file_merchant_stats_merchant_stats_method_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_stats_merchant_stats_method_proto_goTypes,
		DependencyIndexes: file_merchant_stats_merchant_stats_method_proto_depIdxs,
		MessageInfos:      file_merchant_stats_merchant_stats_method_proto_msgTypes,
	}.Build()
	File_merchant_stats_merchant_stats_method_proto = out.File
	file_merchant_stats_merchant_stats_method_proto_goTypes = nil
	file_merchant_stats_merchant_stats_method_proto_depIdxs = nil
}
