package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	errors "github.com/MamangRust/monolith-payment-gateway-shared/errors"

	"github.com/MamangRust/monolith-graphql-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-payment-gateway-pb/user"
	"github.com/MamangRust/monolith-payment-gateway-shared/domain/requests"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.APIResponseUser, error) {
	return ResolverHandle(r.ResolverHandle, "CreateUser", ctx, func(ctx context.Context) (*model.APIResponseUser, error) {
		req := &requests.CreateUserRequest{
			FirstName:       input.Firstname,
			LastName:        input.Lastname,
			Email:           input.Email,
			Password:        input.Password,
			ConfirmPassword: input.ConfirmPassword,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateUserRequest{
			Firstname:       req.FirstName,
			Lastname:        req.LastName,
			Email:           req.Email,
			Password:        req.Password,
			ConfirmPassword: req.ConfirmPassword,
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.Create(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)
		return so, nil
	})
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.APIResponseUser, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateUser", ctx, func(ctx context.Context) (*model.APIResponseUser, error) {
		id := int(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		req := &requests.UpdateUserRequest{
			UserID:          &id,
			FirstName:       input.Firstname,
			LastName:        input.Lastname,
			Email:           input.Email,
			Password:        *input.Password,
			ConfirmPassword: *input.ConfirmPassword,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.UpdateUserRequest{
			Id:              int32(*req.UserID),
			Firstname:       req.FirstName,
			Lastname:        req.LastName,
			Email:           req.Email,
			Password:        req.Password,
			ConfirmPassword: req.ConfirmPassword,
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.Update(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

		r.UserGraphql.Cache.DeleteUserCache(ctx, id)

		return so, nil
	})
}

// TrashedUser is the resolver for the trashedUser field.
func (r *mutationResolver) TrashedUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedUser", ctx, func(ctx context.Context) (*model.APIResponseUserDeleteAt, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.TrashedUser(ctx, &pb.FindByIdUserRequest{Id: id})
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

		r.UserGraphql.Cache.DeleteUserCache(ctx, int(id))

		return so, nil
	})
}

// RestoreUser is the resolver for the restoreUser field.
func (r *mutationResolver) RestoreUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreUser", ctx, func(ctx context.Context) (*model.APIResponseUserDeleteAt, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.RestoreUser(ctx, &pb.FindByIdUserRequest{Id: id})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

		r.UserGraphql.Cache.DeleteUserCache(ctx, int(id))

		return so, nil
	})
}

// DeleteUserPermanent is the resolver for the deleteUserPermanent field.
func (r *mutationResolver) DeleteUserPermanent(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteUserPermanent", ctx, func(ctx context.Context) (*model.APIResponseUserDelete, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		res, err := r.UserGraphql.UserClient.UserCommandClient.DeleteUserPermanent(ctx, &pb.FindByIdUserRequest{Id: id})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteUserPermanent")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserDelete(res)

		r.UserGraphql.Cache.DeleteUserCache(ctx, int(id))

		return so, nil
	})
}

// RestoreAllUser is the resolver for the restoreAllUser field.
func (r *mutationResolver) RestoreAllUser(ctx context.Context) (*model.APIResponseUserAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllUser", ctx, func(ctx context.Context) (*model.APIResponseUserAll, error) {
		res, err := r.UserGraphql.UserClient.UserCommandClient.RestoreAllUser(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)
		return so, nil
	})
}

// DeleteAllUserPermanent is the resolver for the deleteAllUserPermanent field.
func (r *mutationResolver) DeleteAllUserPermanent(ctx context.Context) (*model.APIResponseUserAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllUserPermanent", ctx, func(ctx context.Context) (*model.APIResponseUserAll, error) {
		res, err := r.UserGraphql.UserClient.UserCommandClient.DeleteAllUserPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllUserPermanent")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)
		return so, nil
	})
}

// FindAllUser is the resolver for the findAllUser field.
func (r *queryResolver) FindAllUser(ctx context.Context, input model.FindAllUserInput) (*model.APIResponsePaginationUser, error) {
	// Normalize input for consistent caching and backend request
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	// Use a normalized struct for the cache key
	normalizedInput := &model.FindAllUserInput{
		Page:     &page,
		PageSize: &pageSize,
		Search:   &search,
	}

	cachedData, found := r.UserGraphql.Cache.GetCachedUsersCache(ctx, normalizedInput)
	if found {
		return cachedData, nil
	}

	reqService := &pb.FindAllUserRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	users, errResp := r.UserGraphql.UserClient.UserQueryClient.FindAll(ctx, reqService)
	if errResp != nil {
		return nil, r.handleGraphQLError(errResp, "FindAllUsers")
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUser(users)

	r.UserGraphql.Cache.SetCachedUsersCache(ctx, normalizedInput, so)

	return so, nil
}

// FindByIDUser is the resolver for the findByIdUser field.
func (r *queryResolver) FindByIDUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUser, error) {
	id := int(input.ID)
	if id == 0 {
		return nil, fmt.Errorf("invalid user ID")
	}

	cachedData, found := r.UserGraphql.Cache.GetCachedUserCache(ctx, id)
	if found {
		return cachedData, nil
	}

	user, errResp := r.UserGraphql.UserClient.UserQueryClient.FindById(ctx, &pb.FindByIdUserRequest{
		Id: int32(id),
	})
	if errResp != nil {
		return nil, r.handleGraphQLError(errResp, "FindByIdUser")
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	r.UserGraphql.Cache.SetCachedUserCache(ctx, so)

	return so, nil
}

// FindByActiveUser is the resolver for the findByActiveUser field.
func (r *queryResolver) FindByActiveUser(ctx context.Context, input model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	// Normalize input for consistent caching and backend request
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	// Use a normalized struct for the cache key
	normalizedInput := &model.FindAllUserInput{
		Page:     &page,
		PageSize: &pageSize,
		Search:   &search,
	}

	cachedData, found := r.UserGraphql.Cache.GetCachedUserActiveCache(ctx, normalizedInput)
	if found {
		return cachedData, nil
	}

	reqService := &pb.FindAllUserRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	users, errResp := r.UserGraphql.UserClient.UserQueryClient.FindByActive(ctx, reqService)
	if errResp != nil {
		return nil, r.handleGraphQLError(errResp, "FindByActive")
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUserDeleteAt(users)

	r.UserGraphql.Cache.SetCachedUserActiveCache(ctx, normalizedInput, so)

	return so, nil
}

// FindByTrashedUser is the resolver for the findByTrashedUser field.
func (r *queryResolver) FindByTrashedUser(ctx context.Context, input model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	// Normalize input for consistent caching and backend request
	page := int32(1)
	pageSize := int32(10)
	search := ""

	if input.Page != nil {
		page = int32(*input.Page)
	}
	if input.PageSize != nil {
		pageSize = int32(*input.PageSize)
	}
	if input.Search != nil {
		search = *input.Search
	}

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	normalizedInput := &model.FindAllUserInput{
		Page:     &page,
		PageSize: &pageSize,
		Search:   &search,
	}

	cachedData, found := r.UserGraphql.Cache.GetCachedUserTrashedCache(ctx, normalizedInput)
	if found {
		return cachedData, nil
	}

	reqService := &pb.FindAllUserRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   search,
	}

	users, errResp := r.UserGraphql.UserClient.UserQueryClient.FindByTrashed(ctx, reqService)
	if errResp != nil {
		return nil, r.handleGraphQLError(errResp, "FindByTrashed")
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUserDeleteAt(users)

	r.UserGraphql.Cache.SetCachedUserTrashedCache(ctx, normalizedInput, so)

	return so, nil
}
