// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction/stats/transaction_stats_method.proto

package stats

import (
	transaction "github.com/MamangRust/monolith-payment-gateway-pb/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionMonthMethodResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Month             string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionMonthMethodResponse) Reset() {
	*x = TransactionMonthMethodResponse{}
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthMethodResponse) ProtoMessage() {}

func (x *TransactionMonthMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthMethodResponse.ProtoReflect.Descriptor instead.
func (*TransactionMonthMethodResponse) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_method_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionMonthMethodResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthMethodResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionMonthMethodResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionMonthMethodResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearMethodResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Year              string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionYearMethodResponse) Reset() {
	*x = TransactionYearMethodResponse{}
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearMethodResponse) ProtoMessage() {}

func (x *TransactionYearMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearMethodResponse.ProtoReflect.Descriptor instead.
func (*TransactionYearMethodResponse) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_method_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionYearMethodResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearMethodResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionYearMethodResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionYearMethodResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseTransactionMonthMethod struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthMethodResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthMethod) Reset() {
	*x = ApiResponseTransactionMonthMethod{}
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthMethod) ProtoMessage() {}

func (x *ApiResponseTransactionMonthMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthMethod.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthMethod) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_method_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseTransactionMonthMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthMethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthMethod) GetData() []*TransactionMonthMethodResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearMethod struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearMethodResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearMethod) Reset() {
	*x = ApiResponseTransactionYearMethod{}
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearMethod) ProtoMessage() {}

func (x *ApiResponseTransactionYearMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_method_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearMethod.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearMethod) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_method_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseTransactionYearMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearMethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearMethod) GetData() []*TransactionYearMethodResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_transaction_stats_transaction_stats_method_proto protoreflect.FileDescriptor

const file_transaction_stats_transaction_stats_method_proto_rawDesc = "" +
	"\n" +
	"0transaction/stats/transaction_stats_method.proto\x12\x14pb.transaction.stats\x1a\x1dtransaction/transaction.proto\"\xaf\x01\n" +
	"\x1eTransactionMonthMethodResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\xac\x01\n" +
	"\x1dTransactionYearMethodResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\x9f\x01\n" +
	"!ApiResponseTransactionMonthMethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\x04data\x18\x03 \x03(\v24.pb.transaction.stats.TransactionMonthMethodResponseR\x04data\"\x9d\x01\n" +
	" ApiResponseTransactionYearMethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x04data\x18\x03 \x03(\v23.pb.transaction.stats.TransactionYearMethodResponseR\x04data2\xdc\x04\n" +
	"\x1dTransactionStatsMethodService\x12\x81\x01\n" +
	"\x19FindMonthlyPaymentMethods\x12).pb.transaction.FindYearTransactionStatus\x1a7.pb.transaction.stats.ApiResponseTransactionMonthMethod\"\x00\x12\x7f\n" +
	"\x18FindYearlyPaymentMethods\x12).pb.transaction.FindYearTransactionStatus\x1a6.pb.transaction.stats.ApiResponseTransactionYearMethod\"\x00\x12\x9a\x01\n" +
	"%FindMonthlyPaymentMethodsByCardNumber\x126.pb.transaction.FindByYearCardNumberTransactionRequest\x1a7.pb.transaction.stats.ApiResponseTransactionMonthMethod\"\x00\x12\x98\x01\n" +
	"$FindYearlyPaymentMethodsByCardNumber\x126.pb.transaction.FindByYearCardNumberTransactionRequest\x1a6.pb.transaction.stats.ApiResponseTransactionYearMethod\"\x00BEZCgithub.com/MamangRust/monolith-payment-gateway-pb/transaction/statsb\x06proto3"

var (
	file_transaction_stats_transaction_stats_method_proto_rawDescOnce sync.Once
	file_transaction_stats_transaction_stats_method_proto_rawDescData []byte
)

func file_transaction_stats_transaction_stats_method_proto_rawDescGZIP() []byte {
	file_transaction_stats_transaction_stats_method_proto_rawDescOnce.Do(func() {
		file_transaction_stats_transaction_stats_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_stats_transaction_stats_method_proto_rawDesc), len(file_transaction_stats_transaction_stats_method_proto_rawDesc)))
	})
	return file_transaction_stats_transaction_stats_method_proto_rawDescData
}

var file_transaction_stats_transaction_stats_method_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_stats_transaction_stats_method_proto_goTypes = []any{
	(*TransactionMonthMethodResponse)(nil),                     // 0: pb.transaction.stats.TransactionMonthMethodResponse
	(*TransactionYearMethodResponse)(nil),                      // 1: pb.transaction.stats.TransactionYearMethodResponse
	(*ApiResponseTransactionMonthMethod)(nil),                  // 2: pb.transaction.stats.ApiResponseTransactionMonthMethod
	(*ApiResponseTransactionYearMethod)(nil),                   // 3: pb.transaction.stats.ApiResponseTransactionYearMethod
	(*transaction.FindYearTransactionStatus)(nil),              // 4: pb.transaction.FindYearTransactionStatus
	(*transaction.FindByYearCardNumberTransactionRequest)(nil), // 5: pb.transaction.FindByYearCardNumberTransactionRequest
}
var file_transaction_stats_transaction_stats_method_proto_depIdxs = []int32{
	0, // 0: pb.transaction.stats.ApiResponseTransactionMonthMethod.data:type_name -> pb.transaction.stats.TransactionMonthMethodResponse
	1, // 1: pb.transaction.stats.ApiResponseTransactionYearMethod.data:type_name -> pb.transaction.stats.TransactionYearMethodResponse
	4, // 2: pb.transaction.stats.TransactionStatsMethodService.FindMonthlyPaymentMethods:input_type -> pb.transaction.FindYearTransactionStatus
	4, // 3: pb.transaction.stats.TransactionStatsMethodService.FindYearlyPaymentMethods:input_type -> pb.transaction.FindYearTransactionStatus
	5, // 4: pb.transaction.stats.TransactionStatsMethodService.FindMonthlyPaymentMethodsByCardNumber:input_type -> pb.transaction.FindByYearCardNumberTransactionRequest
	5, // 5: pb.transaction.stats.TransactionStatsMethodService.FindYearlyPaymentMethodsByCardNumber:input_type -> pb.transaction.FindByYearCardNumberTransactionRequest
	2, // 6: pb.transaction.stats.TransactionStatsMethodService.FindMonthlyPaymentMethods:output_type -> pb.transaction.stats.ApiResponseTransactionMonthMethod
	3, // 7: pb.transaction.stats.TransactionStatsMethodService.FindYearlyPaymentMethods:output_type -> pb.transaction.stats.ApiResponseTransactionYearMethod
	2, // 8: pb.transaction.stats.TransactionStatsMethodService.FindMonthlyPaymentMethodsByCardNumber:output_type -> pb.transaction.stats.ApiResponseTransactionMonthMethod
	3, // 9: pb.transaction.stats.TransactionStatsMethodService.FindYearlyPaymentMethodsByCardNumber:output_type -> pb.transaction.stats.ApiResponseTransactionYearMethod
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_stats_transaction_stats_method_proto_init() }
func file_transaction_stats_transaction_stats_method_proto_init() {
	if File_transaction_stats_transaction_stats_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_stats_transaction_stats_method_proto_rawDesc), len(file_transaction_stats_transaction_stats_method_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_stats_transaction_stats_method_proto_goTypes,
		DependencyIndexes: file_transaction_stats_transaction_stats_method_proto_depIdxs,
		MessageInfos:      file_transaction_stats_transaction_stats_method_proto_msgTypes,
	}.Build()
	File_transaction_stats_transaction_stats_method_proto = out.File
	file_transaction_stats_transaction_stats_method_proto_goTypes = nil
	file_transaction_stats_transaction_stats_method_proto_depIdxs = nil
}
