syntax = "proto3";

option go_package = 'github.com/MamangRust/monolith-payment-gateway-pb/topup';

package pb.topup;

import "topup/topup.proto";
import "google/protobuf/empty.proto";

message CreateTopupRequest {
  string card_number = 1;
  string topup_no = 2;
  int32 topup_amount = 3;
  string topup_method = 4;
  string idempotency_key = 5;
}

message UpdateTopupRequest {
  int32 topup_id = 1;
  string card_number = 2;
  int32 topup_amount = 3;
  string topup_method = 4;
}

message ApiResponseTopupDelete {
  string status = 1;
  string message = 2;
}

message ApiResponseTopupAll {
  string status = 1;
  string message = 2;
}

service TopupCommandService {
  rpc CreateTopup(CreateTopupRequest) returns (ApiResponseTopup);
  rpc UpdateTopup(UpdateTopupRequest) returns (ApiResponseTopup);
  rpc TrashedTopup(FindByIdTopupRequest) returns (ApiResponseTopupDeleteAt);
  rpc RestoreTopup(FindByIdTopupRequest) returns (ApiResponseTopupDeleteAt);
  rpc DeleteTopupPermanent(FindByIdTopupRequest)
      returns (ApiResponseTopupDelete);
  rpc RestoreAllTopup(google.protobuf.Empty) returns (ApiResponseTopupAll) {}
  rpc DeleteAllTopupPermanent(google.protobuf.Empty)
      returns (ApiResponseTopupAll) {}
}