apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
  namespace: payment-gateway
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-log-permission
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Setting ownership for /var/log/app"
              chown -R 1000:1000 /var/log/app
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          securityContext:
            runAsUser: 0

        - name: wait-for-kafka
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Waiting for Kafka to be ready (TCP)..."
              until nc -z kafka.payment-gateway.svc.cluster.local 9092; do
                echo "Kafka is not ready yet. Retrying in 5 seconds..."
                sleep 5
              done
              echo "[INIT] Kafka is ready!"
      containers:
        - name: transaction
          image: transaction-service:1.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8088
            - containerPort: 50057
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /metrics
              port: 8088
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
      volumes:
        - name: app-logs
          persistentVolumeClaim:
            claimName: app-logs-pvc
