// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: card/stats/card_stats_balance.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindYearBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearBalance) Reset() {
	*x = FindYearBalance{}
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearBalance) ProtoMessage() {}

func (x *FindYearBalance) ProtoReflect() protoreflect.Message {
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearBalance.ProtoReflect.Descriptor instead.
func (*FindYearBalance) Descriptor() ([]byte, []int) {
	return file_card_stats_card_stats_balance_proto_rawDescGZIP(), []int{0}
}

func (x *FindYearBalance) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearBalanceCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearBalanceCardNumber) Reset() {
	*x = FindYearBalanceCardNumber{}
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearBalanceCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearBalanceCardNumber) ProtoMessage() {}

func (x *FindYearBalanceCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearBalanceCardNumber.ProtoReflect.Descriptor instead.
func (*FindYearBalanceCardNumber) Descriptor() ([]byte, []int) {
	return file_card_stats_card_stats_balance_proto_rawDescGZIP(), []int{1}
}

func (x *FindYearBalanceCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearBalanceCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type CardResponseMonthlyBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalBalance  int64                  `protobuf:"varint,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponseMonthlyBalance) Reset() {
	*x = CardResponseMonthlyBalance{}
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponseMonthlyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponseMonthlyBalance) ProtoMessage() {}

func (x *CardResponseMonthlyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponseMonthlyBalance.ProtoReflect.Descriptor instead.
func (*CardResponseMonthlyBalance) Descriptor() ([]byte, []int) {
	return file_card_stats_card_stats_balance_proto_rawDescGZIP(), []int{2}
}

func (x *CardResponseMonthlyBalance) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CardResponseMonthlyBalance) GetTotalBalance() int64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type CardResponseYearlyBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalBalance  int64                  `protobuf:"varint,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponseYearlyBalance) Reset() {
	*x = CardResponseYearlyBalance{}
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponseYearlyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponseYearlyBalance) ProtoMessage() {}

func (x *CardResponseYearlyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponseYearlyBalance.ProtoReflect.Descriptor instead.
func (*CardResponseYearlyBalance) Descriptor() ([]byte, []int) {
	return file_card_stats_card_stats_balance_proto_rawDescGZIP(), []int{3}
}

func (x *CardResponseYearlyBalance) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CardResponseYearlyBalance) GetTotalBalance() int64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type ApiResponseMonthlyBalance struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        string                        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CardResponseMonthlyBalance `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMonthlyBalance) Reset() {
	*x = ApiResponseMonthlyBalance{}
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMonthlyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMonthlyBalance) ProtoMessage() {}

func (x *ApiResponseMonthlyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMonthlyBalance.ProtoReflect.Descriptor instead.
func (*ApiResponseMonthlyBalance) Descriptor() ([]byte, []int) {
	return file_card_stats_card_stats_balance_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseMonthlyBalance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMonthlyBalance) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMonthlyBalance) GetData() []*CardResponseMonthlyBalance {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseYearlyBalance struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        string                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CardResponseYearlyBalance `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseYearlyBalance) Reset() {
	*x = ApiResponseYearlyBalance{}
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseYearlyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseYearlyBalance) ProtoMessage() {}

func (x *ApiResponseYearlyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_card_stats_card_stats_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseYearlyBalance.ProtoReflect.Descriptor instead.
func (*ApiResponseYearlyBalance) Descriptor() ([]byte, []int) {
	return file_card_stats_card_stats_balance_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseYearlyBalance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseYearlyBalance) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseYearlyBalance) GetData() []*CardResponseYearlyBalance {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_card_stats_card_stats_balance_proto protoreflect.FileDescriptor

const file_card_stats_card_stats_balance_proto_rawDesc = "" +
	"\n" +
	"#card/stats/card_stats_balance.proto\x12\rpb.card.stats\"%\n" +
	"\x0fFindYearBalance\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"P\n" +
	"\x19FindYearBalanceCardNumber\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\"W\n" +
	"\x1aCardResponseMonthlyBalance\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x03R\ftotalBalance\"T\n" +
	"\x19CardResponseYearlyBalance\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x03R\ftotalBalance\"\x8c\x01\n" +
	"\x19ApiResponseMonthlyBalance\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x04data\x18\x03 \x03(\v2).pb.card.stats.CardResponseMonthlyBalanceR\x04data\"\x8a\x01\n" +
	"\x18ApiResponseYearlyBalance\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.pb.card.stats.CardResponseYearlyBalanceR\x04data2\xc9\x03\n" +
	"\x17CardStatsBalanceService\x12`\n" +
	"\x12FindMonthlyBalance\x12\x1e.pb.card.stats.FindYearBalance\x1a(.pb.card.stats.ApiResponseMonthlyBalance\"\x00\x12^\n" +
	"\x11FindYearlyBalance\x12\x1e.pb.card.stats.FindYearBalance\x1a'.pb.card.stats.ApiResponseYearlyBalance\"\x00\x12v\n" +
	"\x1eFindMonthlyBalanceByCardNumber\x12(.pb.card.stats.FindYearBalanceCardNumber\x1a(.pb.card.stats.ApiResponseMonthlyBalance\"\x00\x12t\n" +
	"\x1dFindYearlyBalanceByCardNumber\x12(.pb.card.stats.FindYearBalanceCardNumber\x1a'.pb.card.stats.ApiResponseYearlyBalance\"\x00B>Z<github.com/MamangRust/monolith-payment-gateway-pb/card/statsb\x06proto3"

var (
	file_card_stats_card_stats_balance_proto_rawDescOnce sync.Once
	file_card_stats_card_stats_balance_proto_rawDescData []byte
)

func file_card_stats_card_stats_balance_proto_rawDescGZIP() []byte {
	file_card_stats_card_stats_balance_proto_rawDescOnce.Do(func() {
		file_card_stats_card_stats_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_stats_card_stats_balance_proto_rawDesc), len(file_card_stats_card_stats_balance_proto_rawDesc)))
	})
	return file_card_stats_card_stats_balance_proto_rawDescData
}

var file_card_stats_card_stats_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_card_stats_card_stats_balance_proto_goTypes = []any{
	(*FindYearBalance)(nil),            // 0: pb.card.stats.FindYearBalance
	(*FindYearBalanceCardNumber)(nil),  // 1: pb.card.stats.FindYearBalanceCardNumber
	(*CardResponseMonthlyBalance)(nil), // 2: pb.card.stats.CardResponseMonthlyBalance
	(*CardResponseYearlyBalance)(nil),  // 3: pb.card.stats.CardResponseYearlyBalance
	(*ApiResponseMonthlyBalance)(nil),  // 4: pb.card.stats.ApiResponseMonthlyBalance
	(*ApiResponseYearlyBalance)(nil),   // 5: pb.card.stats.ApiResponseYearlyBalance
}
var file_card_stats_card_stats_balance_proto_depIdxs = []int32{
	2, // 0: pb.card.stats.ApiResponseMonthlyBalance.data:type_name -> pb.card.stats.CardResponseMonthlyBalance
	3, // 1: pb.card.stats.ApiResponseYearlyBalance.data:type_name -> pb.card.stats.CardResponseYearlyBalance
	0, // 2: pb.card.stats.CardStatsBalanceService.FindMonthlyBalance:input_type -> pb.card.stats.FindYearBalance
	0, // 3: pb.card.stats.CardStatsBalanceService.FindYearlyBalance:input_type -> pb.card.stats.FindYearBalance
	1, // 4: pb.card.stats.CardStatsBalanceService.FindMonthlyBalanceByCardNumber:input_type -> pb.card.stats.FindYearBalanceCardNumber
	1, // 5: pb.card.stats.CardStatsBalanceService.FindYearlyBalanceByCardNumber:input_type -> pb.card.stats.FindYearBalanceCardNumber
	4, // 6: pb.card.stats.CardStatsBalanceService.FindMonthlyBalance:output_type -> pb.card.stats.ApiResponseMonthlyBalance
	5, // 7: pb.card.stats.CardStatsBalanceService.FindYearlyBalance:output_type -> pb.card.stats.ApiResponseYearlyBalance
	4, // 8: pb.card.stats.CardStatsBalanceService.FindMonthlyBalanceByCardNumber:output_type -> pb.card.stats.ApiResponseMonthlyBalance
	5, // 9: pb.card.stats.CardStatsBalanceService.FindYearlyBalanceByCardNumber:output_type -> pb.card.stats.ApiResponseYearlyBalance
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_card_stats_card_stats_balance_proto_init() }
func file_card_stats_card_stats_balance_proto_init() {
	if File_card_stats_card_stats_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_stats_card_stats_balance_proto_rawDesc), len(file_card_stats_card_stats_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_stats_card_stats_balance_proto_goTypes,
		DependencyIndexes: file_card_stats_card_stats_balance_proto_depIdxs,
		MessageInfos:      file_card_stats_card_stats_balance_proto_msgTypes,
	}.Build()
	File_card_stats_card_stats_balance_proto = out.File
	file_card_stats_card_stats_balance_proto_goTypes = nil
	file_card_stats_card_stats_balance_proto_depIdxs = nil
}
