// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: card/stats/card_stats_transaction.proto

package stats

import (
	card "github.com/MamangRust/monolith-payment-gateway-pb/card"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_card_stats_card_stats_transaction_proto protoreflect.FileDescriptor

const file_card_stats_card_stats_transaction_proto_rawDesc = "" +
	"\n" +
	"'card/stats/card_stats_transaction.proto\x12\rpb.card.stats\x1a\x0fcard/card.proto2\x87\x05\n" +
	"\x1bCardStatsTransactionService\x12\\\n" +
	"\x1cFindMonthlyTransactionAmount\x12\x17.pb.card.FindYearAmount\x1a!.pb.card.ApiResponseMonthlyAmount\"\x00\x12Z\n" +
	"\x1bFindYearlyTransactionAmount\x12\x17.pb.card.FindYearAmount\x1a .pb.card.ApiResponseYearlyAmount\"\x00\x12r\n" +
	"(FindMonthlyTransactionAmountByCardNumber\x12!.pb.card.FindYearAmountCardNumber\x1a!.pb.card.ApiResponseMonthlyAmount\"\x00\x12p\n" +
	"'FindYearlyTransactionAmountByCardNumber\x12!.pb.card.FindYearAmountCardNumber\x1a .pb.card.ApiResponseYearlyAmount\"\x00\x12X\n" +
	"\x1aFindDailyTransactionAmount\x12\x17.pb.card.FindYearAmount\x1a\x1f.pb.card.ApiResponseDailyAmount\"\x00\x12n\n" +
	"&FindDailyTransactionAmountByCardNumber\x12!.pb.card.FindYearAmountCardNumber\x1a\x1f.pb.card.ApiResponseDailyAmount\"\x00B>Z<github.com/MamangRust/monolith-payment-gateway-pb/card/statsb\x06proto3"

var file_card_stats_card_stats_transaction_proto_goTypes = []any{
	(*card.FindYearAmount)(nil),           // 0: pb.card.FindYearAmount
	(*card.FindYearAmountCardNumber)(nil), // 1: pb.card.FindYearAmountCardNumber
	(*card.ApiResponseMonthlyAmount)(nil), // 2: pb.card.ApiResponseMonthlyAmount
	(*card.ApiResponseYearlyAmount)(nil),  // 3: pb.card.ApiResponseYearlyAmount
	(*card.ApiResponseDailyAmount)(nil),   // 4: pb.card.ApiResponseDailyAmount
}
var file_card_stats_card_stats_transaction_proto_depIdxs = []int32{
	0, // 0: pb.card.stats.CardStatsTransactionService.FindMonthlyTransactionAmount:input_type -> pb.card.FindYearAmount
	0, // 1: pb.card.stats.CardStatsTransactionService.FindYearlyTransactionAmount:input_type -> pb.card.FindYearAmount
	1, // 2: pb.card.stats.CardStatsTransactionService.FindMonthlyTransactionAmountByCardNumber:input_type -> pb.card.FindYearAmountCardNumber
	1, // 3: pb.card.stats.CardStatsTransactionService.FindYearlyTransactionAmountByCardNumber:input_type -> pb.card.FindYearAmountCardNumber
	0, // 4: pb.card.stats.CardStatsTransactionService.FindDailyTransactionAmount:input_type -> pb.card.FindYearAmount
	1, // 5: pb.card.stats.CardStatsTransactionService.FindDailyTransactionAmountByCardNumber:input_type -> pb.card.FindYearAmountCardNumber
	2, // 6: pb.card.stats.CardStatsTransactionService.FindMonthlyTransactionAmount:output_type -> pb.card.ApiResponseMonthlyAmount
	3, // 7: pb.card.stats.CardStatsTransactionService.FindYearlyTransactionAmount:output_type -> pb.card.ApiResponseYearlyAmount
	2, // 8: pb.card.stats.CardStatsTransactionService.FindMonthlyTransactionAmountByCardNumber:output_type -> pb.card.ApiResponseMonthlyAmount
	3, // 9: pb.card.stats.CardStatsTransactionService.FindYearlyTransactionAmountByCardNumber:output_type -> pb.card.ApiResponseYearlyAmount
	4, // 10: pb.card.stats.CardStatsTransactionService.FindDailyTransactionAmount:output_type -> pb.card.ApiResponseDailyAmount
	4, // 11: pb.card.stats.CardStatsTransactionService.FindDailyTransactionAmountByCardNumber:output_type -> pb.card.ApiResponseDailyAmount
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_card_stats_card_stats_transaction_proto_init() }
func file_card_stats_card_stats_transaction_proto_init() {
	if File_card_stats_card_stats_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_stats_card_stats_transaction_proto_rawDesc), len(file_card_stats_card_stats_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_stats_card_stats_transaction_proto_goTypes,
		DependencyIndexes: file_card_stats_card_stats_transaction_proto_depIdxs,
	}.Build()
	File_card_stats_card_stats_transaction_proto = out.File
	file_card_stats_card_stats_transaction_proto_goTypes = nil
	file_card_stats_card_stats_transaction_proto_depIdxs = nil
}
