// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: topup/stats/topup_stats_amount.proto

package stats

import (
	topup "github.com/MamangRust/monolith-payment-gateway-pb/topup"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopupMonthAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupMonthAmountResponse) Reset() {
	*x = TopupMonthAmountResponse{}
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupMonthAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupMonthAmountResponse) ProtoMessage() {}

func (x *TopupMonthAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupMonthAmountResponse.ProtoReflect.Descriptor instead.
func (*TopupMonthAmountResponse) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_amount_proto_rawDescGZIP(), []int{0}
}

func (x *TopupMonthAmountResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TopupMonthAmountResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TopupYearlyAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupYearlyAmountResponse) Reset() {
	*x = TopupYearlyAmountResponse{}
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupYearlyAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupYearlyAmountResponse) ProtoMessage() {}

func (x *TopupYearlyAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupYearlyAmountResponse.ProtoReflect.Descriptor instead.
func (*TopupYearlyAmountResponse) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_amount_proto_rawDescGZIP(), []int{1}
}

func (x *TopupYearlyAmountResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TopupYearlyAmountResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseTopupMonthAmount struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TopupMonthAmountResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopupMonthAmount) Reset() {
	*x = ApiResponseTopupMonthAmount{}
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopupMonthAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopupMonthAmount) ProtoMessage() {}

func (x *ApiResponseTopupMonthAmount) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopupMonthAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseTopupMonthAmount) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_amount_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseTopupMonthAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopupMonthAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopupMonthAmount) GetData() []*TopupMonthAmountResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTopupYearAmount struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        string                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TopupYearlyAmountResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopupYearAmount) Reset() {
	*x = ApiResponseTopupYearAmount{}
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopupYearAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopupYearAmount) ProtoMessage() {}

func (x *ApiResponseTopupYearAmount) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_amount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopupYearAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseTopupYearAmount) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_amount_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseTopupYearAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopupYearAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopupYearAmount) GetData() []*TopupYearlyAmountResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_topup_stats_topup_stats_amount_proto protoreflect.FileDescriptor

const file_topup_stats_topup_stats_amount_proto_rawDesc = "" +
	"\n" +
	"$topup/stats/topup_stats_amount.proto\x12\x0epb.topup.stats\x1a\x11topup/topup.proto\"S\n" +
	"\x18TopupMonthAmountResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x05R\vtotalAmount\"R\n" +
	"\x19TopupYearlyAmountResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x05R\vtotalAmount\"\x8d\x01\n" +
	"\x1bApiResponseTopupMonthAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.pb.topup.stats.TopupMonthAmountResponseR\x04data\"\x8d\x01\n" +
	"\x1aApiResponseTopupYearAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x04data\x18\x03 \x03(\v2).pb.topup.stats.TopupYearlyAmountResponseR\x04data2\xd9\x03\n" +
	"\x17TopupStatsAmountService\x12g\n" +
	"\x17FindMonthlyTopupAmounts\x12\x1d.pb.topup.FindYearTopupStatus\x1a+.pb.topup.stats.ApiResponseTopupMonthAmount\"\x00\x12e\n" +
	"\x16FindYearlyTopupAmounts\x12\x1d.pb.topup.FindYearTopupStatus\x1a*.pb.topup.stats.ApiResponseTopupYearAmount\"\x00\x12w\n" +
	"#FindMonthlyTopupAmountsByCardNumber\x12!.pb.topup.FindYearTopupCardNumber\x1a+.pb.topup.stats.ApiResponseTopupMonthAmount\"\x00\x12u\n" +
	"\"FindYearlyTopupAmountsByCardNumber\x12!.pb.topup.FindYearTopupCardNumber\x1a*.pb.topup.stats.ApiResponseTopupYearAmount\"\x00B?Z=github.com/MamangRust/monolith-payment-gateway-pb/topup/statsb\x06proto3"

var (
	file_topup_stats_topup_stats_amount_proto_rawDescOnce sync.Once
	file_topup_stats_topup_stats_amount_proto_rawDescData []byte
)

func file_topup_stats_topup_stats_amount_proto_rawDescGZIP() []byte {
	file_topup_stats_topup_stats_amount_proto_rawDescOnce.Do(func() {
		file_topup_stats_topup_stats_amount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topup_stats_topup_stats_amount_proto_rawDesc), len(file_topup_stats_topup_stats_amount_proto_rawDesc)))
	})
	return file_topup_stats_topup_stats_amount_proto_rawDescData
}

var file_topup_stats_topup_stats_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_topup_stats_topup_stats_amount_proto_goTypes = []any{
	(*TopupMonthAmountResponse)(nil),      // 0: pb.topup.stats.TopupMonthAmountResponse
	(*TopupYearlyAmountResponse)(nil),     // 1: pb.topup.stats.TopupYearlyAmountResponse
	(*ApiResponseTopupMonthAmount)(nil),   // 2: pb.topup.stats.ApiResponseTopupMonthAmount
	(*ApiResponseTopupYearAmount)(nil),    // 3: pb.topup.stats.ApiResponseTopupYearAmount
	(*topup.FindYearTopupStatus)(nil),     // 4: pb.topup.FindYearTopupStatus
	(*topup.FindYearTopupCardNumber)(nil), // 5: pb.topup.FindYearTopupCardNumber
}
var file_topup_stats_topup_stats_amount_proto_depIdxs = []int32{
	0, // 0: pb.topup.stats.ApiResponseTopupMonthAmount.data:type_name -> pb.topup.stats.TopupMonthAmountResponse
	1, // 1: pb.topup.stats.ApiResponseTopupYearAmount.data:type_name -> pb.topup.stats.TopupYearlyAmountResponse
	4, // 2: pb.topup.stats.TopupStatsAmountService.FindMonthlyTopupAmounts:input_type -> pb.topup.FindYearTopupStatus
	4, // 3: pb.topup.stats.TopupStatsAmountService.FindYearlyTopupAmounts:input_type -> pb.topup.FindYearTopupStatus
	5, // 4: pb.topup.stats.TopupStatsAmountService.FindMonthlyTopupAmountsByCardNumber:input_type -> pb.topup.FindYearTopupCardNumber
	5, // 5: pb.topup.stats.TopupStatsAmountService.FindYearlyTopupAmountsByCardNumber:input_type -> pb.topup.FindYearTopupCardNumber
	2, // 6: pb.topup.stats.TopupStatsAmountService.FindMonthlyTopupAmounts:output_type -> pb.topup.stats.ApiResponseTopupMonthAmount
	3, // 7: pb.topup.stats.TopupStatsAmountService.FindYearlyTopupAmounts:output_type -> pb.topup.stats.ApiResponseTopupYearAmount
	2, // 8: pb.topup.stats.TopupStatsAmountService.FindMonthlyTopupAmountsByCardNumber:output_type -> pb.topup.stats.ApiResponseTopupMonthAmount
	3, // 9: pb.topup.stats.TopupStatsAmountService.FindYearlyTopupAmountsByCardNumber:output_type -> pb.topup.stats.ApiResponseTopupYearAmount
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_topup_stats_topup_stats_amount_proto_init() }
func file_topup_stats_topup_stats_amount_proto_init() {
	if File_topup_stats_topup_stats_amount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topup_stats_topup_stats_amount_proto_rawDesc), len(file_topup_stats_topup_stats_amount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topup_stats_topup_stats_amount_proto_goTypes,
		DependencyIndexes: file_topup_stats_topup_stats_amount_proto_depIdxs,
		MessageInfos:      file_topup_stats_topup_stats_amount_proto_msgTypes,
	}.Build()
	File_topup_stats_topup_stats_amount_proto = out.File
	file_topup_stats_topup_stats_amount_proto_goTypes = nil
	file_topup_stats_topup_stats_amount_proto_depIdxs = nil
}
