// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: topup/stats/topup_stats_status.proto

package stats

import (
	topup "github.com/MamangRust/monolith-payment-gateway-pb/topup"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopupMonthStatusSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalSuccess  int32                  `protobuf:"varint,3,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupMonthStatusSuccessResponse) Reset() {
	*x = TopupMonthStatusSuccessResponse{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupMonthStatusSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupMonthStatusSuccessResponse) ProtoMessage() {}

func (x *TopupMonthStatusSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupMonthStatusSuccessResponse.ProtoReflect.Descriptor instead.
func (*TopupMonthStatusSuccessResponse) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{0}
}

func (x *TopupMonthStatusSuccessResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TopupMonthStatusSuccessResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TopupMonthStatusSuccessResponse) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *TopupMonthStatusSuccessResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TopupYearStatusSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalSuccess  int32                  `protobuf:"varint,2,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupYearStatusSuccessResponse) Reset() {
	*x = TopupYearStatusSuccessResponse{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupYearStatusSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupYearStatusSuccessResponse) ProtoMessage() {}

func (x *TopupYearStatusSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupYearStatusSuccessResponse.ProtoReflect.Descriptor instead.
func (*TopupYearStatusSuccessResponse) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{1}
}

func (x *TopupYearStatusSuccessResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TopupYearStatusSuccessResponse) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *TopupYearStatusSuccessResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TopupMonthStatusFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupMonthStatusFailedResponse) Reset() {
	*x = TopupMonthStatusFailedResponse{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupMonthStatusFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupMonthStatusFailedResponse) ProtoMessage() {}

func (x *TopupMonthStatusFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupMonthStatusFailedResponse.ProtoReflect.Descriptor instead.
func (*TopupMonthStatusFailedResponse) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{2}
}

func (x *TopupMonthStatusFailedResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TopupMonthStatusFailedResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TopupMonthStatusFailedResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *TopupMonthStatusFailedResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TopupYearStatusFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,2,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupYearStatusFailedResponse) Reset() {
	*x = TopupYearStatusFailedResponse{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupYearStatusFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupYearStatusFailedResponse) ProtoMessage() {}

func (x *TopupYearStatusFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupYearStatusFailedResponse.ProtoReflect.Descriptor instead.
func (*TopupYearStatusFailedResponse) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{3}
}

func (x *TopupYearStatusFailedResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TopupYearStatusFailedResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *TopupYearStatusFailedResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseTopupMonthStatusSuccess struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        string                             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TopupMonthStatusSuccessResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopupMonthStatusSuccess) Reset() {
	*x = ApiResponseTopupMonthStatusSuccess{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopupMonthStatusSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopupMonthStatusSuccess) ProtoMessage() {}

func (x *ApiResponseTopupMonthStatusSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopupMonthStatusSuccess.ProtoReflect.Descriptor instead.
func (*ApiResponseTopupMonthStatusSuccess) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseTopupMonthStatusSuccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopupMonthStatusSuccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopupMonthStatusSuccess) GetData() []*TopupMonthStatusSuccessResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTopupYearStatusSuccess struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TopupYearStatusSuccessResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopupYearStatusSuccess) Reset() {
	*x = ApiResponseTopupYearStatusSuccess{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopupYearStatusSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopupYearStatusSuccess) ProtoMessage() {}

func (x *ApiResponseTopupYearStatusSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopupYearStatusSuccess.ProtoReflect.Descriptor instead.
func (*ApiResponseTopupYearStatusSuccess) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseTopupYearStatusSuccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopupYearStatusSuccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopupYearStatusSuccess) GetData() []*TopupYearStatusSuccessResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTopupMonthStatusFailed struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TopupMonthStatusFailedResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopupMonthStatusFailed) Reset() {
	*x = ApiResponseTopupMonthStatusFailed{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopupMonthStatusFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopupMonthStatusFailed) ProtoMessage() {}

func (x *ApiResponseTopupMonthStatusFailed) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopupMonthStatusFailed.ProtoReflect.Descriptor instead.
func (*ApiResponseTopupMonthStatusFailed) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseTopupMonthStatusFailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopupMonthStatusFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopupMonthStatusFailed) GetData() []*TopupMonthStatusFailedResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTopupYearStatusFailed struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TopupYearStatusFailedResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTopupYearStatusFailed) Reset() {
	*x = ApiResponseTopupYearStatusFailed{}
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTopupYearStatusFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTopupYearStatusFailed) ProtoMessage() {}

func (x *ApiResponseTopupYearStatusFailed) ProtoReflect() protoreflect.Message {
	mi := &file_topup_stats_topup_stats_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTopupYearStatusFailed.ProtoReflect.Descriptor instead.
func (*ApiResponseTopupYearStatusFailed) Descriptor() ([]byte, []int) {
	return file_topup_stats_topup_stats_status_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseTopupYearStatusFailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTopupYearStatusFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTopupYearStatusFailed) GetData() []*TopupYearStatusFailedResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_topup_stats_topup_stats_status_proto protoreflect.FileDescriptor

const file_topup_stats_topup_stats_status_proto_rawDesc = "" +
	"\n" +
	"$topup/stats/topup_stats_status.proto\x12\x0epb.topup.stats\x1a\x11topup/topup.proto\"\x93\x01\n" +
	"\x1fTopupMonthStatusSuccessResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12#\n" +
	"\rtotal_success\x18\x03 \x01(\x05R\ftotalSuccess\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"|\n" +
	"\x1eTopupYearStatusSuccessResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12#\n" +
	"\rtotal_success\x18\x02 \x01(\x05R\ftotalSuccess\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\x90\x01\n" +
	"\x1eTopupMonthStatusFailedResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x05R\vtotalFailed\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"y\n" +
	"\x1dTopupYearStatusFailedResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_failed\x18\x02 \x01(\x05R\vtotalFailed\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\x9b\x01\n" +
	"\"ApiResponseTopupMonthStatusSuccess\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x04data\x18\x03 \x03(\v2/.pb.topup.stats.TopupMonthStatusSuccessResponseR\x04data\"\x99\x01\n" +
	"!ApiResponseTopupYearStatusSuccess\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x04data\x18\x03 \x03(\v2..pb.topup.stats.TopupYearStatusSuccessResponseR\x04data\"\x99\x01\n" +
	"!ApiResponseTopupMonthStatusFailed\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x04data\x18\x03 \x03(\v2..pb.topup.stats.TopupMonthStatusFailedResponseR\x04data\"\x97\x01\n" +
	" ApiResponseTopupYearStatusFailed\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x04data\x18\x03 \x03(\v2-.pb.topup.stats.TopupYearStatusFailedResponseR\x04data2\xa1\b\n" +
	"\x17TopupStatsStatusService\x12w\n" +
	"\x1dFindMonthlyTopupStatusSuccess\x12 .pb.topup.FindMonthlyTopupStatus\x1a2.pb.topup.stats.ApiResponseTopupMonthStatusSuccess\"\x00\x12r\n" +
	"\x1cFindYearlyTopupStatusSuccess\x12\x1d.pb.topup.FindYearTopupStatus\x1a1.pb.topup.stats.ApiResponseTopupYearStatusSuccess\"\x00\x12u\n" +
	"\x1cFindMonthlyTopupStatusFailed\x12 .pb.topup.FindMonthlyTopupStatus\x1a1.pb.topup.stats.ApiResponseTopupMonthStatusFailed\"\x00\x12p\n" +
	"\x1bFindYearlyTopupStatusFailed\x12\x1d.pb.topup.FindYearTopupStatus\x1a0.pb.topup.stats.ApiResponseTopupYearStatusFailed\"\x00\x12\x8d\x01\n" +
	")FindMonthlyTopupStatusSuccessByCardNumber\x12*.pb.topup.FindMonthlyTopupStatusCardNumber\x1a2.pb.topup.stats.ApiResponseTopupMonthStatusSuccess\"\x00\x12\x88\x01\n" +
	"(FindYearlyTopupStatusSuccessByCardNumber\x12'.pb.topup.FindYearTopupStatusCardNumber\x1a1.pb.topup.stats.ApiResponseTopupYearStatusSuccess\"\x00\x12\x8b\x01\n" +
	"(FindMonthlyTopupStatusFailedByCardNumber\x12*.pb.topup.FindMonthlyTopupStatusCardNumber\x1a1.pb.topup.stats.ApiResponseTopupMonthStatusFailed\"\x00\x12\x86\x01\n" +
	"'FindYearlyTopupStatusFailedByCardNumber\x12'.pb.topup.FindYearTopupStatusCardNumber\x1a0.pb.topup.stats.ApiResponseTopupYearStatusFailed\"\x00B?Z=github.com/MamangRust/monolith-payment-gateway-pb/topup/statsb\x06proto3"

var (
	file_topup_stats_topup_stats_status_proto_rawDescOnce sync.Once
	file_topup_stats_topup_stats_status_proto_rawDescData []byte
)

func file_topup_stats_topup_stats_status_proto_rawDescGZIP() []byte {
	file_topup_stats_topup_stats_status_proto_rawDescOnce.Do(func() {
		file_topup_stats_topup_stats_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topup_stats_topup_stats_status_proto_rawDesc), len(file_topup_stats_topup_stats_status_proto_rawDesc)))
	})
	return file_topup_stats_topup_stats_status_proto_rawDescData
}

var file_topup_stats_topup_stats_status_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_topup_stats_topup_stats_status_proto_goTypes = []any{
	(*TopupMonthStatusSuccessResponse)(nil),        // 0: pb.topup.stats.TopupMonthStatusSuccessResponse
	(*TopupYearStatusSuccessResponse)(nil),         // 1: pb.topup.stats.TopupYearStatusSuccessResponse
	(*TopupMonthStatusFailedResponse)(nil),         // 2: pb.topup.stats.TopupMonthStatusFailedResponse
	(*TopupYearStatusFailedResponse)(nil),          // 3: pb.topup.stats.TopupYearStatusFailedResponse
	(*ApiResponseTopupMonthStatusSuccess)(nil),     // 4: pb.topup.stats.ApiResponseTopupMonthStatusSuccess
	(*ApiResponseTopupYearStatusSuccess)(nil),      // 5: pb.topup.stats.ApiResponseTopupYearStatusSuccess
	(*ApiResponseTopupMonthStatusFailed)(nil),      // 6: pb.topup.stats.ApiResponseTopupMonthStatusFailed
	(*ApiResponseTopupYearStatusFailed)(nil),       // 7: pb.topup.stats.ApiResponseTopupYearStatusFailed
	(*topup.FindMonthlyTopupStatus)(nil),           // 8: pb.topup.FindMonthlyTopupStatus
	(*topup.FindYearTopupStatus)(nil),              // 9: pb.topup.FindYearTopupStatus
	(*topup.FindMonthlyTopupStatusCardNumber)(nil), // 10: pb.topup.FindMonthlyTopupStatusCardNumber
	(*topup.FindYearTopupStatusCardNumber)(nil),    // 11: pb.topup.FindYearTopupStatusCardNumber
}
var file_topup_stats_topup_stats_status_proto_depIdxs = []int32{
	0,  // 0: pb.topup.stats.ApiResponseTopupMonthStatusSuccess.data:type_name -> pb.topup.stats.TopupMonthStatusSuccessResponse
	1,  // 1: pb.topup.stats.ApiResponseTopupYearStatusSuccess.data:type_name -> pb.topup.stats.TopupYearStatusSuccessResponse
	2,  // 2: pb.topup.stats.ApiResponseTopupMonthStatusFailed.data:type_name -> pb.topup.stats.TopupMonthStatusFailedResponse
	3,  // 3: pb.topup.stats.ApiResponseTopupYearStatusFailed.data:type_name -> pb.topup.stats.TopupYearStatusFailedResponse
	8,  // 4: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusSuccess:input_type -> pb.topup.FindMonthlyTopupStatus
	9,  // 5: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusSuccess:input_type -> pb.topup.FindYearTopupStatus
	8,  // 6: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusFailed:input_type -> pb.topup.FindMonthlyTopupStatus
	9,  // 7: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusFailed:input_type -> pb.topup.FindYearTopupStatus
	10, // 8: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusSuccessByCardNumber:input_type -> pb.topup.FindMonthlyTopupStatusCardNumber
	11, // 9: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusSuccessByCardNumber:input_type -> pb.topup.FindYearTopupStatusCardNumber
	10, // 10: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusFailedByCardNumber:input_type -> pb.topup.FindMonthlyTopupStatusCardNumber
	11, // 11: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusFailedByCardNumber:input_type -> pb.topup.FindYearTopupStatusCardNumber
	4,  // 12: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusSuccess:output_type -> pb.topup.stats.ApiResponseTopupMonthStatusSuccess
	5,  // 13: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusSuccess:output_type -> pb.topup.stats.ApiResponseTopupYearStatusSuccess
	6,  // 14: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusFailed:output_type -> pb.topup.stats.ApiResponseTopupMonthStatusFailed
	7,  // 15: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusFailed:output_type -> pb.topup.stats.ApiResponseTopupYearStatusFailed
	4,  // 16: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusSuccessByCardNumber:output_type -> pb.topup.stats.ApiResponseTopupMonthStatusSuccess
	5,  // 17: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusSuccessByCardNumber:output_type -> pb.topup.stats.ApiResponseTopupYearStatusSuccess
	6,  // 18: pb.topup.stats.TopupStatsStatusService.FindMonthlyTopupStatusFailedByCardNumber:output_type -> pb.topup.stats.ApiResponseTopupMonthStatusFailed
	7,  // 19: pb.topup.stats.TopupStatsStatusService.FindYearlyTopupStatusFailedByCardNumber:output_type -> pb.topup.stats.ApiResponseTopupYearStatusFailed
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_topup_stats_topup_stats_status_proto_init() }
func file_topup_stats_topup_stats_status_proto_init() {
	if File_topup_stats_topup_stats_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topup_stats_topup_stats_status_proto_rawDesc), len(file_topup_stats_topup_stats_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topup_stats_topup_stats_status_proto_goTypes,
		DependencyIndexes: file_topup_stats_topup_stats_status_proto_depIdxs,
		MessageInfos:      file_topup_stats_topup_stats_status_proto_msgTypes,
	}.Build()
	File_topup_stats_topup_stats_status_proto = out.File
	file_topup_stats_topup_stats_status_proto_goTypes = nil
	file_topup_stats_topup_stats_status_proto_depIdxs = nil
}
