// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant/merchant_transaction.proto

package merchant

import (
	common "github.com/MamangRust/monolith-payment-gateway-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantTransactionResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber      string                  `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount          int32                   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                  `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MerchantId      int32                   `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName    string                  `protobuf:"bytes,6,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	TransactionTime string                  `protobuf:"bytes,7,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	CreatedAt       string                  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MerchantTransactionResponse) Reset() {
	*x = MerchantTransactionResponse{}
	mi := &file_merchant_merchant_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantTransactionResponse) ProtoMessage() {}

func (x *MerchantTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_merchant_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantTransactionResponse.ProtoReflect.Descriptor instead.
func (*MerchantTransactionResponse) Descriptor() ([]byte, []int) {
	return file_merchant_merchant_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantTransactionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantTransactionResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *MerchantTransactionResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MerchantTransactionResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *MerchantTransactionResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantTransactionResponse) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *MerchantTransactionResponse) GetTransactionTime() string {
	if x != nil {
		return x.TransactionTime
	}
	return ""
}

func (x *MerchantTransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantTransactionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MerchantTransactionResponse) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponsePaginationMerchantTransaction struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Status         string                         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*MerchantTransactionResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta         `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantTransaction) Reset() {
	*x = ApiResponsePaginationMerchantTransaction{}
	mi := &file_merchant_merchant_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantTransaction) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_merchant_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantTransaction) Descriptor() ([]byte, []int) {
	return file_merchant_merchant_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationMerchantTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantTransaction) GetData() []*MerchantTransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantTransaction) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

var File_merchant_merchant_transaction_proto protoreflect.FileDescriptor

const file_merchant_merchant_transaction_proto_rawDesc = "" +
	"\n" +
	"#merchant/merchant_transaction.proto\x12\vpb.merchant\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17merchant/merchant.proto\x1a\x10common/api.proto\"\xf9\x02\n" +
	"\x1bMerchantTransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x05R\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x06 \x01(\tR\fmerchantName\x12)\n" +
	"\x10transaction_time\x18\a \x01(\tR\x0ftransactionTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"\xdd\x01\n" +
	"(ApiResponsePaginationMerchantTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.pb.merchant.MerchantTransactionResponseR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta2\x96\x03\n" +
	"\x1aMerchantTransactionService\x12z\n" +
	"\x1aFindAllTransactionMerchant\x12#.pb.merchant.FindAllMerchantRequest\x1a5.pb.merchant.ApiResponsePaginationMerchantTransaction\"\x00\x12y\n" +
	"\x1aFindAllTransactionByApikey\x12\".pb.merchant.FindAllMerchantApikey\x1a5.pb.merchant.ApiResponsePaginationMerchantTransaction\"\x00\x12\x80\x01\n" +
	"\x1cFindAllTransactionByMerchant\x12'.pb.merchant.FindAllMerchantTransaction\x1a5.pb.merchant.ApiResponsePaginationMerchantTransaction\"\x00B<Z:github.com/MamangRust/monolith-payment-gateway-pb/merchantb\x06proto3"

var (
	file_merchant_merchant_transaction_proto_rawDescOnce sync.Once
	file_merchant_merchant_transaction_proto_rawDescData []byte
)

func file_merchant_merchant_transaction_proto_rawDescGZIP() []byte {
	file_merchant_merchant_transaction_proto_rawDescOnce.Do(func() {
		file_merchant_merchant_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_merchant_transaction_proto_rawDesc), len(file_merchant_merchant_transaction_proto_rawDesc)))
	})
	return file_merchant_merchant_transaction_proto_rawDescData
}

var file_merchant_merchant_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_merchant_merchant_transaction_proto_goTypes = []any{
	(*MerchantTransactionResponse)(nil),              // 0: pb.merchant.MerchantTransactionResponse
	(*ApiResponsePaginationMerchantTransaction)(nil), // 1: pb.merchant.ApiResponsePaginationMerchantTransaction
	(*wrapperspb.StringValue)(nil),                   // 2: google.protobuf.StringValue
	(*common.PaginationMeta)(nil),                    // 3: pb.common.PaginationMeta
	(*FindAllMerchantRequest)(nil),                   // 4: pb.merchant.FindAllMerchantRequest
	(*FindAllMerchantApikey)(nil),                    // 5: pb.merchant.FindAllMerchantApikey
	(*FindAllMerchantTransaction)(nil),               // 6: pb.merchant.FindAllMerchantTransaction
}
var file_merchant_merchant_transaction_proto_depIdxs = []int32{
	2, // 0: pb.merchant.MerchantTransactionResponse.deleted_at:type_name -> google.protobuf.StringValue
	0, // 1: pb.merchant.ApiResponsePaginationMerchantTransaction.data:type_name -> pb.merchant.MerchantTransactionResponse
	3, // 2: pb.merchant.ApiResponsePaginationMerchantTransaction.paginationMeta:type_name -> pb.common.PaginationMeta
	4, // 3: pb.merchant.MerchantTransactionService.FindAllTransactionMerchant:input_type -> pb.merchant.FindAllMerchantRequest
	5, // 4: pb.merchant.MerchantTransactionService.FindAllTransactionByApikey:input_type -> pb.merchant.FindAllMerchantApikey
	6, // 5: pb.merchant.MerchantTransactionService.FindAllTransactionByMerchant:input_type -> pb.merchant.FindAllMerchantTransaction
	1, // 6: pb.merchant.MerchantTransactionService.FindAllTransactionMerchant:output_type -> pb.merchant.ApiResponsePaginationMerchantTransaction
	1, // 7: pb.merchant.MerchantTransactionService.FindAllTransactionByApikey:output_type -> pb.merchant.ApiResponsePaginationMerchantTransaction
	1, // 8: pb.merchant.MerchantTransactionService.FindAllTransactionByMerchant:output_type -> pb.merchant.ApiResponsePaginationMerchantTransaction
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_merchant_merchant_transaction_proto_init() }
func file_merchant_merchant_transaction_proto_init() {
	if File_merchant_merchant_transaction_proto != nil {
		return
	}
	file_merchant_merchant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_merchant_transaction_proto_rawDesc), len(file_merchant_merchant_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_merchant_transaction_proto_goTypes,
		DependencyIndexes: file_merchant_merchant_transaction_proto_depIdxs,
		MessageInfos:      file_merchant_merchant_transaction_proto_msgTypes,
	}.Build()
	File_merchant_merchant_transaction_proto = out.File
	file_merchant_merchant_transaction_proto_goTypes = nil
	file_merchant_merchant_transaction_proto_depIdxs = nil
}
