// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant/merchant_query.proto

package merchant

import (
	common "github.com/MamangRust/monolith-payment-gateway-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponsePaginationMerchant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*MerchantResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchant) Reset() {
	*x = ApiResponsePaginationMerchant{}
	mi := &file_merchant_merchant_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchant) ProtoMessage() {}

func (x *ApiResponsePaginationMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_merchant_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchant.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchant) Descriptor() ([]byte, []int) {
	return file_merchant_merchant_query_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponsePaginationMerchant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchant) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchant) GetData() []*MerchantResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchant) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type ApiResponsePaginationMerchantDeleteAt struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Status         string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*MerchantResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *common.PaginationMeta      `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDeleteAt) Reset() {
	*x = ApiResponsePaginationMerchantDeleteAt{}
	mi := &file_merchant_merchant_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_merchant_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_merchant_query_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetData() []*MerchantResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetPaginationMeta() *common.PaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

var File_merchant_merchant_query_proto protoreflect.FileDescriptor

const file_merchant_merchant_query_proto_rawDesc = "" +
	"\n" +
	"\x1dmerchant/merchant_query.proto\x12\vpb.merchant\x1a\x10common/api.proto\x1a\x17merchant/merchant.proto\"\xc7\x01\n" +
	"\x1dApiResponsePaginationMerchant\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.merchant.MerchantResponseR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta\"\xd7\x01\n" +
	"%ApiResponsePaginationMerchantDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.pb.merchant.MerchantResponseDeleteAtR\x04data\x12A\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\x0epaginationMeta2\xee\x04\n" +
	"\x14MerchantQueryService\x12d\n" +
	"\x0fFindAllMerchant\x12#.pb.merchant.FindAllMerchantRequest\x1a*.pb.merchant.ApiResponsePaginationMerchant\"\x00\x12\\\n" +
	"\x10FindByIdMerchant\x12$.pb.merchant.FindByIdMerchantRequest\x1a .pb.merchant.ApiResponseMerchant\"\x00\x12T\n" +
	"\fFindByApiKey\x12 .pb.merchant.FindByApiKeyRequest\x1a .pb.merchant.ApiResponseMerchant\"\x00\x12e\n" +
	"\x14FindByMerchantUserId\x12(.pb.merchant.FindByMerchantUserIdRequest\x1a!.pb.merchant.ApiResponsesMerchant\"\x00\x12i\n" +
	"\fFindByActive\x12#.pb.merchant.FindAllMerchantRequest\x1a2.pb.merchant.ApiResponsePaginationMerchantDeleteAt\"\x00\x12j\n" +
	"\rFindByTrashed\x12#.pb.merchant.FindAllMerchantRequest\x1a2.pb.merchant.ApiResponsePaginationMerchantDeleteAt\"\x00B<Z:github.com/MamangRust/monolith-payment-gateway-pb/merchantb\x06proto3"

var (
	file_merchant_merchant_query_proto_rawDescOnce sync.Once
	file_merchant_merchant_query_proto_rawDescData []byte
)

func file_merchant_merchant_query_proto_rawDescGZIP() []byte {
	file_merchant_merchant_query_proto_rawDescOnce.Do(func() {
		file_merchant_merchant_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_merchant_query_proto_rawDesc), len(file_merchant_merchant_query_proto_rawDesc)))
	})
	return file_merchant_merchant_query_proto_rawDescData
}

var file_merchant_merchant_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_merchant_merchant_query_proto_goTypes = []any{
	(*ApiResponsePaginationMerchant)(nil),         // 0: pb.merchant.ApiResponsePaginationMerchant
	(*ApiResponsePaginationMerchantDeleteAt)(nil), // 1: pb.merchant.ApiResponsePaginationMerchantDeleteAt
	(*MerchantResponse)(nil),                      // 2: pb.merchant.MerchantResponse
	(*common.PaginationMeta)(nil),                 // 3: pb.common.PaginationMeta
	(*MerchantResponseDeleteAt)(nil),              // 4: pb.merchant.MerchantResponseDeleteAt
	(*FindAllMerchantRequest)(nil),                // 5: pb.merchant.FindAllMerchantRequest
	(*FindByIdMerchantRequest)(nil),               // 6: pb.merchant.FindByIdMerchantRequest
	(*FindByApiKeyRequest)(nil),                   // 7: pb.merchant.FindByApiKeyRequest
	(*FindByMerchantUserIdRequest)(nil),           // 8: pb.merchant.FindByMerchantUserIdRequest
	(*ApiResponseMerchant)(nil),                   // 9: pb.merchant.ApiResponseMerchant
	(*ApiResponsesMerchant)(nil),                  // 10: pb.merchant.ApiResponsesMerchant
}
var file_merchant_merchant_query_proto_depIdxs = []int32{
	2,  // 0: pb.merchant.ApiResponsePaginationMerchant.data:type_name -> pb.merchant.MerchantResponse
	3,  // 1: pb.merchant.ApiResponsePaginationMerchant.paginationMeta:type_name -> pb.common.PaginationMeta
	4,  // 2: pb.merchant.ApiResponsePaginationMerchantDeleteAt.data:type_name -> pb.merchant.MerchantResponseDeleteAt
	3,  // 3: pb.merchant.ApiResponsePaginationMerchantDeleteAt.paginationMeta:type_name -> pb.common.PaginationMeta
	5,  // 4: pb.merchant.MerchantQueryService.FindAllMerchant:input_type -> pb.merchant.FindAllMerchantRequest
	6,  // 5: pb.merchant.MerchantQueryService.FindByIdMerchant:input_type -> pb.merchant.FindByIdMerchantRequest
	7,  // 6: pb.merchant.MerchantQueryService.FindByApiKey:input_type -> pb.merchant.FindByApiKeyRequest
	8,  // 7: pb.merchant.MerchantQueryService.FindByMerchantUserId:input_type -> pb.merchant.FindByMerchantUserIdRequest
	5,  // 8: pb.merchant.MerchantQueryService.FindByActive:input_type -> pb.merchant.FindAllMerchantRequest
	5,  // 9: pb.merchant.MerchantQueryService.FindByTrashed:input_type -> pb.merchant.FindAllMerchantRequest
	0,  // 10: pb.merchant.MerchantQueryService.FindAllMerchant:output_type -> pb.merchant.ApiResponsePaginationMerchant
	9,  // 11: pb.merchant.MerchantQueryService.FindByIdMerchant:output_type -> pb.merchant.ApiResponseMerchant
	9,  // 12: pb.merchant.MerchantQueryService.FindByApiKey:output_type -> pb.merchant.ApiResponseMerchant
	10, // 13: pb.merchant.MerchantQueryService.FindByMerchantUserId:output_type -> pb.merchant.ApiResponsesMerchant
	1,  // 14: pb.merchant.MerchantQueryService.FindByActive:output_type -> pb.merchant.ApiResponsePaginationMerchantDeleteAt
	1,  // 15: pb.merchant.MerchantQueryService.FindByTrashed:output_type -> pb.merchant.ApiResponsePaginationMerchantDeleteAt
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_merchant_merchant_query_proto_init() }
func file_merchant_merchant_query_proto_init() {
	if File_merchant_merchant_query_proto != nil {
		return
	}
	file_merchant_merchant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_merchant_query_proto_rawDesc), len(file_merchant_merchant_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_merchant_query_proto_goTypes,
		DependencyIndexes: file_merchant_merchant_query_proto_depIdxs,
		MessageInfos:      file_merchant_merchant_query_proto_msgTypes,
	}.Build()
	File_merchant_merchant_query_proto = out.File
	file_merchant_merchant_query_proto_goTypes = nil
	file_merchant_merchant_query_proto_depIdxs = nil
}
