// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: withdraw/withdraw.proto

package withdraw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindYearWithdrawStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearWithdrawStatus) Reset() {
	*x = FindYearWithdrawStatus{}
	mi := &file_withdraw_withdraw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearWithdrawStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearWithdrawStatus) ProtoMessage() {}

func (x *FindYearWithdrawStatus) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearWithdrawStatus.ProtoReflect.Descriptor instead.
func (*FindYearWithdrawStatus) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{0}
}

func (x *FindYearWithdrawStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindMonthlyWithdrawStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyWithdrawStatus) Reset() {
	*x = FindMonthlyWithdrawStatus{}
	mi := &file_withdraw_withdraw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyWithdrawStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyWithdrawStatus) ProtoMessage() {}

func (x *FindMonthlyWithdrawStatus) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyWithdrawStatus.ProtoReflect.Descriptor instead.
func (*FindMonthlyWithdrawStatus) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{1}
}

func (x *FindMonthlyWithdrawStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyWithdrawStatus) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearWithdrawStatusCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearWithdrawStatusCardNumber) Reset() {
	*x = FindYearWithdrawStatusCardNumber{}
	mi := &file_withdraw_withdraw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearWithdrawStatusCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearWithdrawStatusCardNumber) ProtoMessage() {}

func (x *FindYearWithdrawStatusCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearWithdrawStatusCardNumber.ProtoReflect.Descriptor instead.
func (*FindYearWithdrawStatusCardNumber) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{2}
}

func (x *FindYearWithdrawStatusCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindYearWithdrawStatusCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindMonthlyWithdrawStatusCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyWithdrawStatusCardNumber) Reset() {
	*x = FindMonthlyWithdrawStatusCardNumber{}
	mi := &file_withdraw_withdraw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyWithdrawStatusCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyWithdrawStatusCardNumber) ProtoMessage() {}

func (x *FindMonthlyWithdrawStatusCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyWithdrawStatusCardNumber.ProtoReflect.Descriptor instead.
func (*FindMonthlyWithdrawStatusCardNumber) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{3}
}

func (x *FindMonthlyWithdrawStatusCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindMonthlyWithdrawStatusCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyWithdrawStatusCardNumber) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearWithdrawCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearWithdrawCardNumber) Reset() {
	*x = FindYearWithdrawCardNumber{}
	mi := &file_withdraw_withdraw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearWithdrawCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearWithdrawCardNumber) ProtoMessage() {}

func (x *FindYearWithdrawCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearWithdrawCardNumber.ProtoReflect.Descriptor instead.
func (*FindYearWithdrawCardNumber) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{4}
}

func (x *FindYearWithdrawCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindYearWithdrawCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindAllWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllWithdrawRequest) Reset() {
	*x = FindAllWithdrawRequest{}
	mi := &file_withdraw_withdraw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllWithdrawRequest) ProtoMessage() {}

func (x *FindAllWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllWithdrawRequest.ProtoReflect.Descriptor instead.
func (*FindAllWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllWithdrawRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllWithdrawRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllWithdrawRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllWithdrawByCardNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllWithdrawByCardNumberRequest) Reset() {
	*x = FindAllWithdrawByCardNumberRequest{}
	mi := &file_withdraw_withdraw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllWithdrawByCardNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllWithdrawByCardNumberRequest) ProtoMessage() {}

func (x *FindAllWithdrawByCardNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllWithdrawByCardNumberRequest.ProtoReflect.Descriptor instead.
func (*FindAllWithdrawByCardNumberRequest) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllWithdrawByCardNumberRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindAllWithdrawByCardNumberRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllWithdrawByCardNumberRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllWithdrawByCardNumberRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId    int32                  `protobuf:"varint,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdWithdrawRequest) Reset() {
	*x = FindByIdWithdrawRequest{}
	mi := &file_withdraw_withdraw_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdWithdrawRequest) ProtoMessage() {}

func (x *FindByIdWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdWithdrawRequest.ProtoReflect.Descriptor instead.
func (*FindByIdWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{7}
}

func (x *FindByIdWithdrawRequest) GetWithdrawId() int32 {
	if x != nil {
		return x.WithdrawId
	}
	return 0
}

type WithdrawResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId     int32                  `protobuf:"varint,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	WithdrawNo     string                 `protobuf:"bytes,2,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	CardNumber     string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	WithdrawAmount int32                  `protobuf:"varint,4,opt,name=withdraw_amount,json=withdrawAmount,proto3" json:"withdraw_amount,omitempty"`
	WithdrawTime   string                 `protobuf:"bytes,5,opt,name=withdraw_time,json=withdrawTime,proto3" json:"withdraw_time,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_withdraw_withdraw_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawResponse) GetWithdrawId() int32 {
	if x != nil {
		return x.WithdrawId
	}
	return 0
}

func (x *WithdrawResponse) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

func (x *WithdrawResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *WithdrawResponse) GetWithdrawAmount() int32 {
	if x != nil {
		return x.WithdrawAmount
	}
	return 0
}

func (x *WithdrawResponse) GetWithdrawTime() string {
	if x != nil {
		return x.WithdrawTime
	}
	return ""
}

func (x *WithdrawResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WithdrawResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WithdrawResponseDeleteAt struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	WithdrawId     int32                   `protobuf:"varint,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	WithdrawNo     string                  `protobuf:"bytes,2,opt,name=withdraw_no,json=withdrawNo,proto3" json:"withdraw_no,omitempty"`
	CardNumber     string                  `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	WithdrawAmount int32                   `protobuf:"varint,4,opt,name=withdraw_amount,json=withdrawAmount,proto3" json:"withdraw_amount,omitempty"`
	WithdrawTime   string                  `protobuf:"bytes,5,opt,name=withdraw_time,json=withdrawTime,proto3" json:"withdraw_time,omitempty"`
	CreatedAt      string                  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WithdrawResponseDeleteAt) Reset() {
	*x = WithdrawResponseDeleteAt{}
	mi := &file_withdraw_withdraw_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponseDeleteAt) ProtoMessage() {}

func (x *WithdrawResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*WithdrawResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawResponseDeleteAt) GetWithdrawId() int32 {
	if x != nil {
		return x.WithdrawId
	}
	return 0
}

func (x *WithdrawResponseDeleteAt) GetWithdrawNo() string {
	if x != nil {
		return x.WithdrawNo
	}
	return ""
}

func (x *WithdrawResponseDeleteAt) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *WithdrawResponseDeleteAt) GetWithdrawAmount() int32 {
	if x != nil {
		return x.WithdrawAmount
	}
	return 0
}

func (x *WithdrawResponseDeleteAt) GetWithdrawTime() string {
	if x != nil {
		return x.WithdrawTime
	}
	return ""
}

func (x *WithdrawResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WithdrawResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *WithdrawResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponsesWithdraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*WithdrawResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesWithdraw) Reset() {
	*x = ApiResponsesWithdraw{}
	mi := &file_withdraw_withdraw_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesWithdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesWithdraw) ProtoMessage() {}

func (x *ApiResponsesWithdraw) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesWithdraw.ProtoReflect.Descriptor instead.
func (*ApiResponsesWithdraw) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponsesWithdraw) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesWithdraw) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesWithdraw) GetData() []*WithdrawResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseWithdraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *WithdrawResponse      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseWithdraw) Reset() {
	*x = ApiResponseWithdraw{}
	mi := &file_withdraw_withdraw_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseWithdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseWithdraw) ProtoMessage() {}

func (x *ApiResponseWithdraw) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseWithdraw.ProtoReflect.Descriptor instead.
func (*ApiResponseWithdraw) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponseWithdraw) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseWithdraw) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseWithdraw) GetData() *WithdrawResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApIResponseWithdrawDeleteAt struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *WithdrawResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApIResponseWithdrawDeleteAt) Reset() {
	*x = ApIResponseWithdrawDeleteAt{}
	mi := &file_withdraw_withdraw_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApIResponseWithdrawDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApIResponseWithdrawDeleteAt) ProtoMessage() {}

func (x *ApIResponseWithdrawDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_withdraw_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApIResponseWithdrawDeleteAt.ProtoReflect.Descriptor instead.
func (*ApIResponseWithdrawDeleteAt) Descriptor() ([]byte, []int) {
	return file_withdraw_withdraw_proto_rawDescGZIP(), []int{12}
}

func (x *ApIResponseWithdrawDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApIResponseWithdrawDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApIResponseWithdrawDeleteAt) GetData() *WithdrawResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_withdraw_withdraw_proto protoreflect.FileDescriptor

const file_withdraw_withdraw_proto_rawDesc = "" +
	"\n" +
	"\x17withdraw/withdraw.proto\x12\vpb.withdraw\x1a\x1egoogle/protobuf/wrappers.proto\",\n" +
	"\x16FindYearWithdrawStatus\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"E\n" +
	"\x19FindMonthlyWithdrawStatus\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"W\n" +
	" FindYearWithdrawStatusCardNumber\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"p\n" +
	"#FindMonthlyWithdrawStatusCardNumber\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"Q\n" +
	"\x1aFindYearWithdrawCardNumber\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"a\n" +
	"\x16FindAllWithdrawRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x8e\x01\n" +
	"\"FindAllWithdrawByCardNumberRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\":\n" +
	"\x17FindByIdWithdrawRequest\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\x05R\n" +
	"withdrawId\"\x81\x02\n" +
	"\x10WithdrawResponse\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\x05R\n" +
	"withdrawId\x12\x1f\n" +
	"\vwithdraw_no\x18\x02 \x01(\tR\n" +
	"withdrawNo\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12'\n" +
	"\x0fwithdraw_amount\x18\x04 \x01(\x05R\x0ewithdrawAmount\x12#\n" +
	"\rwithdraw_time\x18\x05 \x01(\tR\fwithdrawTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xc6\x02\n" +
	"\x18WithdrawResponseDeleteAt\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\x05R\n" +
	"withdrawId\x12\x1f\n" +
	"\vwithdraw_no\x18\x02 \x01(\tR\n" +
	"withdrawNo\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12'\n" +
	"\x0fwithdraw_amount\x18\x04 \x01(\x05R\x0ewithdrawAmount\x12#\n" +
	"\rwithdraw_time\x18\x05 \x01(\tR\fwithdrawTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"{\n" +
	"\x14ApiResponsesWithdraw\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.withdraw.WithdrawResponseR\x04data\"z\n" +
	"\x13ApiResponseWithdraw\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.pb.withdraw.WithdrawResponseR\x04data\"\x8a\x01\n" +
	"\x1bApIResponseWithdrawDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2%.pb.withdraw.WithdrawResponseDeleteAtR\x04dataB<Z:github.com/MamangRust/monolith-payment-gateway-pb/withdrawb\x06proto3"

var (
	file_withdraw_withdraw_proto_rawDescOnce sync.Once
	file_withdraw_withdraw_proto_rawDescData []byte
)

func file_withdraw_withdraw_proto_rawDescGZIP() []byte {
	file_withdraw_withdraw_proto_rawDescOnce.Do(func() {
		file_withdraw_withdraw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_withdraw_withdraw_proto_rawDesc), len(file_withdraw_withdraw_proto_rawDesc)))
	})
	return file_withdraw_withdraw_proto_rawDescData
}

var file_withdraw_withdraw_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_withdraw_withdraw_proto_goTypes = []any{
	(*FindYearWithdrawStatus)(nil),              // 0: pb.withdraw.FindYearWithdrawStatus
	(*FindMonthlyWithdrawStatus)(nil),           // 1: pb.withdraw.FindMonthlyWithdrawStatus
	(*FindYearWithdrawStatusCardNumber)(nil),    // 2: pb.withdraw.FindYearWithdrawStatusCardNumber
	(*FindMonthlyWithdrawStatusCardNumber)(nil), // 3: pb.withdraw.FindMonthlyWithdrawStatusCardNumber
	(*FindYearWithdrawCardNumber)(nil),          // 4: pb.withdraw.FindYearWithdrawCardNumber
	(*FindAllWithdrawRequest)(nil),              // 5: pb.withdraw.FindAllWithdrawRequest
	(*FindAllWithdrawByCardNumberRequest)(nil),  // 6: pb.withdraw.FindAllWithdrawByCardNumberRequest
	(*FindByIdWithdrawRequest)(nil),             // 7: pb.withdraw.FindByIdWithdrawRequest
	(*WithdrawResponse)(nil),                    // 8: pb.withdraw.WithdrawResponse
	(*WithdrawResponseDeleteAt)(nil),            // 9: pb.withdraw.WithdrawResponseDeleteAt
	(*ApiResponsesWithdraw)(nil),                // 10: pb.withdraw.ApiResponsesWithdraw
	(*ApiResponseWithdraw)(nil),                 // 11: pb.withdraw.ApiResponseWithdraw
	(*ApIResponseWithdrawDeleteAt)(nil),         // 12: pb.withdraw.ApIResponseWithdrawDeleteAt
	(*wrapperspb.StringValue)(nil),              // 13: google.protobuf.StringValue
}
var file_withdraw_withdraw_proto_depIdxs = []int32{
	13, // 0: pb.withdraw.WithdrawResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	8,  // 1: pb.withdraw.ApiResponsesWithdraw.data:type_name -> pb.withdraw.WithdrawResponse
	8,  // 2: pb.withdraw.ApiResponseWithdraw.data:type_name -> pb.withdraw.WithdrawResponse
	9,  // 3: pb.withdraw.ApIResponseWithdrawDeleteAt.data:type_name -> pb.withdraw.WithdrawResponseDeleteAt
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_withdraw_withdraw_proto_init() }
func file_withdraw_withdraw_proto_init() {
	if File_withdraw_withdraw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_withdraw_withdraw_proto_rawDesc), len(file_withdraw_withdraw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_withdraw_withdraw_proto_goTypes,
		DependencyIndexes: file_withdraw_withdraw_proto_depIdxs,
		MessageInfos:      file_withdraw_withdraw_proto_msgTypes,
	}.Build()
	File_withdraw_withdraw_proto = out.File
	file_withdraw_withdraw_proto_goTypes = nil
	file_withdraw_withdraw_proto_depIdxs = nil
}
