// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: saldo/stats/saldo_stats_balance.proto

package stats

import (
	context "context"
	saldo "github.com/MamangRust/monolith-payment-gateway-pb/saldo"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SaldoStatsBalanceService_FindMonthlySaldoBalances_FullMethodName = "/pb.saldo.stats.SaldoStatsBalanceService/FindMonthlySaldoBalances"
	SaldoStatsBalanceService_FindYearlySaldoBalances_FullMethodName  = "/pb.saldo.stats.SaldoStatsBalanceService/FindYearlySaldoBalances"
)

// SaldoStatsBalanceServiceClient is the client API for SaldoStatsBalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaldoStatsBalanceServiceClient interface {
	FindMonthlySaldoBalances(ctx context.Context, in *saldo.FindYearlySaldo, opts ...grpc.CallOption) (*ApiResponseMonthSaldoBalances, error)
	FindYearlySaldoBalances(ctx context.Context, in *saldo.FindYearlySaldo, opts ...grpc.CallOption) (*ApiResponseYearSaldoBalances, error)
}

type saldoStatsBalanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaldoStatsBalanceServiceClient(cc grpc.ClientConnInterface) SaldoStatsBalanceServiceClient {
	return &saldoStatsBalanceServiceClient{cc}
}

func (c *saldoStatsBalanceServiceClient) FindMonthlySaldoBalances(ctx context.Context, in *saldo.FindYearlySaldo, opts ...grpc.CallOption) (*ApiResponseMonthSaldoBalances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMonthSaldoBalances)
	err := c.cc.Invoke(ctx, SaldoStatsBalanceService_FindMonthlySaldoBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saldoStatsBalanceServiceClient) FindYearlySaldoBalances(ctx context.Context, in *saldo.FindYearlySaldo, opts ...grpc.CallOption) (*ApiResponseYearSaldoBalances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseYearSaldoBalances)
	err := c.cc.Invoke(ctx, SaldoStatsBalanceService_FindYearlySaldoBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaldoStatsBalanceServiceServer is the server API for SaldoStatsBalanceService service.
// All implementations must embed UnimplementedSaldoStatsBalanceServiceServer
// for forward compatibility.
type SaldoStatsBalanceServiceServer interface {
	FindMonthlySaldoBalances(context.Context, *saldo.FindYearlySaldo) (*ApiResponseMonthSaldoBalances, error)
	FindYearlySaldoBalances(context.Context, *saldo.FindYearlySaldo) (*ApiResponseYearSaldoBalances, error)
	mustEmbedUnimplementedSaldoStatsBalanceServiceServer()
}

// UnimplementedSaldoStatsBalanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSaldoStatsBalanceServiceServer struct{}

func (UnimplementedSaldoStatsBalanceServiceServer) FindMonthlySaldoBalances(context.Context, *saldo.FindYearlySaldo) (*ApiResponseMonthSaldoBalances, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlySaldoBalances not implemented")
}
func (UnimplementedSaldoStatsBalanceServiceServer) FindYearlySaldoBalances(context.Context, *saldo.FindYearlySaldo) (*ApiResponseYearSaldoBalances, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlySaldoBalances not implemented")
}
func (UnimplementedSaldoStatsBalanceServiceServer) mustEmbedUnimplementedSaldoStatsBalanceServiceServer() {
}
func (UnimplementedSaldoStatsBalanceServiceServer) testEmbeddedByValue() {}

// UnsafeSaldoStatsBalanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaldoStatsBalanceServiceServer will
// result in compilation errors.
type UnsafeSaldoStatsBalanceServiceServer interface {
	mustEmbedUnimplementedSaldoStatsBalanceServiceServer()
}

func RegisterSaldoStatsBalanceServiceServer(s grpc.ServiceRegistrar, srv SaldoStatsBalanceServiceServer) {
	// If the following call panics, it indicates UnimplementedSaldoStatsBalanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaldoStatsBalanceService_ServiceDesc, srv)
}

func _SaldoStatsBalanceService_FindMonthlySaldoBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(saldo.FindYearlySaldo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaldoStatsBalanceServiceServer).FindMonthlySaldoBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaldoStatsBalanceService_FindMonthlySaldoBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaldoStatsBalanceServiceServer).FindMonthlySaldoBalances(ctx, req.(*saldo.FindYearlySaldo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaldoStatsBalanceService_FindYearlySaldoBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(saldo.FindYearlySaldo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaldoStatsBalanceServiceServer).FindYearlySaldoBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaldoStatsBalanceService_FindYearlySaldoBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaldoStatsBalanceServiceServer).FindYearlySaldoBalances(ctx, req.(*saldo.FindYearlySaldo))
	}
	return interceptor(ctx, in, info, handler)
}

// SaldoStatsBalanceService_ServiceDesc is the grpc.ServiceDesc for SaldoStatsBalanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaldoStatsBalanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.saldo.stats.SaldoStatsBalanceService",
	HandlerType: (*SaldoStatsBalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlySaldoBalances",
			Handler:    _SaldoStatsBalanceService_FindMonthlySaldoBalances_Handler,
		},
		{
			MethodName: "FindYearlySaldoBalances",
			Handler:    _SaldoStatsBalanceService_FindYearlySaldoBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saldo/stats/saldo_stats_balance.proto",
}
