// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: saldo/stats/saldo_stats_total.proto

package stats

import (
	saldo "github.com/MamangRust/monolith-payment-gateway-pb/saldo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaldoMonthTotalBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Year          string                 `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	TotalBalance  int32                  `protobuf:"varint,3,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaldoMonthTotalBalanceResponse) Reset() {
	*x = SaldoMonthTotalBalanceResponse{}
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaldoMonthTotalBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaldoMonthTotalBalanceResponse) ProtoMessage() {}

func (x *SaldoMonthTotalBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaldoMonthTotalBalanceResponse.ProtoReflect.Descriptor instead.
func (*SaldoMonthTotalBalanceResponse) Descriptor() ([]byte, []int) {
	return file_saldo_stats_saldo_stats_total_proto_rawDescGZIP(), []int{0}
}

func (x *SaldoMonthTotalBalanceResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *SaldoMonthTotalBalanceResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *SaldoMonthTotalBalanceResponse) GetTotalBalance() int32 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type SaldoYearTotalBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalBalance  int32                  `protobuf:"varint,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaldoYearTotalBalanceResponse) Reset() {
	*x = SaldoYearTotalBalanceResponse{}
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaldoYearTotalBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaldoYearTotalBalanceResponse) ProtoMessage() {}

func (x *SaldoYearTotalBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaldoYearTotalBalanceResponse.ProtoReflect.Descriptor instead.
func (*SaldoYearTotalBalanceResponse) Descriptor() ([]byte, []int) {
	return file_saldo_stats_saldo_stats_total_proto_rawDescGZIP(), []int{1}
}

func (x *SaldoYearTotalBalanceResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *SaldoYearTotalBalanceResponse) GetTotalBalance() int32 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type ApiResponseMonthTotalSaldo struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SaldoMonthTotalBalanceResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMonthTotalSaldo) Reset() {
	*x = ApiResponseMonthTotalSaldo{}
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMonthTotalSaldo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMonthTotalSaldo) ProtoMessage() {}

func (x *ApiResponseMonthTotalSaldo) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMonthTotalSaldo.ProtoReflect.Descriptor instead.
func (*ApiResponseMonthTotalSaldo) Descriptor() ([]byte, []int) {
	return file_saldo_stats_saldo_stats_total_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseMonthTotalSaldo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMonthTotalSaldo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMonthTotalSaldo) GetData() []*SaldoMonthTotalBalanceResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseYearTotalSaldo struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SaldoYearTotalBalanceResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseYearTotalSaldo) Reset() {
	*x = ApiResponseYearTotalSaldo{}
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseYearTotalSaldo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseYearTotalSaldo) ProtoMessage() {}

func (x *ApiResponseYearTotalSaldo) ProtoReflect() protoreflect.Message {
	mi := &file_saldo_stats_saldo_stats_total_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseYearTotalSaldo.ProtoReflect.Descriptor instead.
func (*ApiResponseYearTotalSaldo) Descriptor() ([]byte, []int) {
	return file_saldo_stats_saldo_stats_total_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseYearTotalSaldo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseYearTotalSaldo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseYearTotalSaldo) GetData() []*SaldoYearTotalBalanceResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_saldo_stats_saldo_stats_total_proto protoreflect.FileDescriptor

const file_saldo_stats_saldo_stats_total_proto_rawDesc = "" +
	"\n" +
	"#saldo/stats/saldo_stats_total.proto\x12\x0epb.saldo.stats\x1a\x11saldo/saldo.proto\"o\n" +
	"\x1eSaldoMonthTotalBalanceResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x12\n" +
	"\x04year\x18\x02 \x01(\tR\x04year\x12#\n" +
	"\rtotal_balance\x18\x03 \x01(\x05R\ftotalBalance\"X\n" +
	"\x1dSaldoYearTotalBalanceResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x05R\ftotalBalance\"\x92\x01\n" +
	"\x1aApiResponseMonthTotalSaldo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x04data\x18\x03 \x03(\v2..pb.saldo.stats.SaldoMonthTotalBalanceResponseR\x04data\"\x90\x01\n" +
	"\x19ApiResponseYearTotalSaldo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x04data\x18\x03 \x03(\v2-.pb.saldo.stats.SaldoYearTotalBalanceResponseR\x04data2\xf3\x01\n" +
	"\x16SaldoStatsTotalBalance\x12t\n" +
	"\x1cFindMonthlyTotalSaldoBalance\x12&.pb.saldo.FindMonthlySaldoTotalBalance\x1a*.pb.saldo.stats.ApiResponseMonthTotalSaldo\"\x00\x12c\n" +
	"\x19FindYearTotalSaldoBalance\x12\x19.pb.saldo.FindYearlySaldo\x1a).pb.saldo.stats.ApiResponseYearTotalSaldo\"\x00B?Z=github.com/MamangRust/monolith-payment-gateway-pb/saldo/statsb\x06proto3"

var (
	file_saldo_stats_saldo_stats_total_proto_rawDescOnce sync.Once
	file_saldo_stats_saldo_stats_total_proto_rawDescData []byte
)

func file_saldo_stats_saldo_stats_total_proto_rawDescGZIP() []byte {
	file_saldo_stats_saldo_stats_total_proto_rawDescOnce.Do(func() {
		file_saldo_stats_saldo_stats_total_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saldo_stats_saldo_stats_total_proto_rawDesc), len(file_saldo_stats_saldo_stats_total_proto_rawDesc)))
	})
	return file_saldo_stats_saldo_stats_total_proto_rawDescData
}

var file_saldo_stats_saldo_stats_total_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_saldo_stats_saldo_stats_total_proto_goTypes = []any{
	(*SaldoMonthTotalBalanceResponse)(nil),     // 0: pb.saldo.stats.SaldoMonthTotalBalanceResponse
	(*SaldoYearTotalBalanceResponse)(nil),      // 1: pb.saldo.stats.SaldoYearTotalBalanceResponse
	(*ApiResponseMonthTotalSaldo)(nil),         // 2: pb.saldo.stats.ApiResponseMonthTotalSaldo
	(*ApiResponseYearTotalSaldo)(nil),          // 3: pb.saldo.stats.ApiResponseYearTotalSaldo
	(*saldo.FindMonthlySaldoTotalBalance)(nil), // 4: pb.saldo.FindMonthlySaldoTotalBalance
	(*saldo.FindYearlySaldo)(nil),              // 5: pb.saldo.FindYearlySaldo
}
var file_saldo_stats_saldo_stats_total_proto_depIdxs = []int32{
	0, // 0: pb.saldo.stats.ApiResponseMonthTotalSaldo.data:type_name -> pb.saldo.stats.SaldoMonthTotalBalanceResponse
	1, // 1: pb.saldo.stats.ApiResponseYearTotalSaldo.data:type_name -> pb.saldo.stats.SaldoYearTotalBalanceResponse
	4, // 2: pb.saldo.stats.SaldoStatsTotalBalance.FindMonthlyTotalSaldoBalance:input_type -> pb.saldo.FindMonthlySaldoTotalBalance
	5, // 3: pb.saldo.stats.SaldoStatsTotalBalance.FindYearTotalSaldoBalance:input_type -> pb.saldo.FindYearlySaldo
	2, // 4: pb.saldo.stats.SaldoStatsTotalBalance.FindMonthlyTotalSaldoBalance:output_type -> pb.saldo.stats.ApiResponseMonthTotalSaldo
	3, // 5: pb.saldo.stats.SaldoStatsTotalBalance.FindYearTotalSaldoBalance:output_type -> pb.saldo.stats.ApiResponseYearTotalSaldo
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_saldo_stats_saldo_stats_total_proto_init() }
func file_saldo_stats_saldo_stats_total_proto_init() {
	if File_saldo_stats_saldo_stats_total_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saldo_stats_saldo_stats_total_proto_rawDesc), len(file_saldo_stats_saldo_stats_total_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saldo_stats_saldo_stats_total_proto_goTypes,
		DependencyIndexes: file_saldo_stats_saldo_stats_total_proto_depIdxs,
		MessageInfos:      file_saldo_stats_saldo_stats_total_proto_msgTypes,
	}.Build()
	File_saldo_stats_saldo_stats_total_proto = out.File
	file_saldo_stats_saldo_stats_total_proto_goTypes = nil
	file_saldo_stats_saldo_stats_total_proto_depIdxs = nil
}
