apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-gateway-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: payment-gateway
  source:
    repoURL: https://github.com/MamangRust/monolith-payment-gateway-grpc.git
    targetRevision: main
    path: deployments/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: payment-gateway
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
