// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transfer/transfer_command.proto

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferFrom   string                 `protobuf:"bytes,1,opt,name=transfer_from,json=transferFrom,proto3" json:"transfer_from,omitempty"`
	TransferTo     string                 `protobuf:"bytes,2,opt,name=transfer_to,json=transferTo,proto3" json:"transfer_to,omitempty"`
	TransferAmount int32                  `protobuf:"varint,3,opt,name=transfer_amount,json=transferAmount,proto3" json:"transfer_amount,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_transfer_transfer_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_transfer_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_transfer_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransferRequest) GetTransferFrom() string {
	if x != nil {
		return x.TransferFrom
	}
	return ""
}

func (x *CreateTransferRequest) GetTransferTo() string {
	if x != nil {
		return x.TransferTo
	}
	return ""
}

func (x *CreateTransferRequest) GetTransferAmount() int32 {
	if x != nil {
		return x.TransferAmount
	}
	return 0
}

func (x *CreateTransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpdateTransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     int32                  `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	TransferFrom   string                 `protobuf:"bytes,2,opt,name=transfer_from,json=transferFrom,proto3" json:"transfer_from,omitempty"`
	TransferTo     string                 `protobuf:"bytes,3,opt,name=transfer_to,json=transferTo,proto3" json:"transfer_to,omitempty"`
	TransferAmount int32                  `protobuf:"varint,4,opt,name=transfer_amount,json=transferAmount,proto3" json:"transfer_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTransferRequest) Reset() {
	*x = UpdateTransferRequest{}
	mi := &file_transfer_transfer_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransferRequest) ProtoMessage() {}

func (x *UpdateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_transfer_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransferRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_transfer_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTransferRequest) GetTransferId() int32 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *UpdateTransferRequest) GetTransferFrom() string {
	if x != nil {
		return x.TransferFrom
	}
	return ""
}

func (x *UpdateTransferRequest) GetTransferTo() string {
	if x != nil {
		return x.TransferTo
	}
	return ""
}

func (x *UpdateTransferRequest) GetTransferAmount() int32 {
	if x != nil {
		return x.TransferAmount
	}
	return 0
}

type ApiResponseTransferDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransferDelete) Reset() {
	*x = ApiResponseTransferDelete{}
	mi := &file_transfer_transfer_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransferDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransferDelete) ProtoMessage() {}

func (x *ApiResponseTransferDelete) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_transfer_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransferDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseTransferDelete) Descriptor() ([]byte, []int) {
	return file_transfer_transfer_command_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseTransferDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransferDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseTransferAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransferAll) Reset() {
	*x = ApiResponseTransferAll{}
	mi := &file_transfer_transfer_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransferAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransferAll) ProtoMessage() {}

func (x *ApiResponseTransferAll) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_transfer_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransferAll.ProtoReflect.Descriptor instead.
func (*ApiResponseTransferAll) Descriptor() ([]byte, []int) {
	return file_transfer_transfer_command_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseTransferAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransferAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transfer_transfer_command_proto protoreflect.FileDescriptor

const file_transfer_transfer_command_proto_rawDesc = "" +
	"\n" +
	"\x1ftransfer/transfer_command.proto\x12\vpb.transfer\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17transfer/transfer.proto\"\xaf\x01\n" +
	"\x15CreateTransferRequest\x12#\n" +
	"\rtransfer_from\x18\x01 \x01(\tR\ftransferFrom\x12\x1f\n" +
	"\vtransfer_to\x18\x02 \x01(\tR\n" +
	"transferTo\x12'\n" +
	"\x0ftransfer_amount\x18\x03 \x01(\x05R\x0etransferAmount\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\xa7\x01\n" +
	"\x15UpdateTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\x05R\n" +
	"transferId\x12#\n" +
	"\rtransfer_from\x18\x02 \x01(\tR\ftransferFrom\x12\x1f\n" +
	"\vtransfer_to\x18\x03 \x01(\tR\n" +
	"transferTo\x12'\n" +
	"\x0ftransfer_amount\x18\x04 \x01(\x05R\x0etransferAmount\"M\n" +
	"\x19ApiResponseTransferDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x16ApiResponseTransferAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa9\x05\n" +
	"\x16TransferCommandService\x12V\n" +
	"\x0eCreateTransfer\x12\".pb.transfer.CreateTransferRequest\x1a .pb.transfer.ApiResponseTransfer\x12V\n" +
	"\x0eUpdateTransfer\x12\".pb.transfer.UpdateTransferRequest\x1a .pb.transfer.ApiResponseTransfer\x12a\n" +
	"\x0fTrashedTransfer\x12$.pb.transfer.FindByIdTransferRequest\x1a(.pb.transfer.ApIResponseTransferDeleteAt\x12a\n" +
	"\x0fRestoreTransfer\x12$.pb.transfer.FindByIdTransferRequest\x1a(.pb.transfer.ApIResponseTransferDeleteAt\x12g\n" +
	"\x17DeleteTransferPermanent\x12$.pb.transfer.FindByIdTransferRequest\x1a&.pb.transfer.ApiResponseTransferDelete\x12S\n" +
	"\x12RestoreAllTransfer\x12\x16.google.protobuf.Empty\x1a#.pb.transfer.ApiResponseTransferAll\"\x00\x12[\n" +
	"\x1aDeleteAllTransferPermanent\x12\x16.google.protobuf.Empty\x1a#.pb.transfer.ApiResponseTransferAll\"\x00B<Z:github.com/MamangRust/monolith-payment-gateway-pb/transferb\x06proto3"

var (
	file_transfer_transfer_command_proto_rawDescOnce sync.Once
	file_transfer_transfer_command_proto_rawDescData []byte
)

func file_transfer_transfer_command_proto_rawDescGZIP() []byte {
	file_transfer_transfer_command_proto_rawDescOnce.Do(func() {
		file_transfer_transfer_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_transfer_command_proto_rawDesc), len(file_transfer_transfer_command_proto_rawDesc)))
	})
	return file_transfer_transfer_command_proto_rawDescData
}

var file_transfer_transfer_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transfer_transfer_command_proto_goTypes = []any{
	(*CreateTransferRequest)(nil),       // 0: pb.transfer.CreateTransferRequest
	(*UpdateTransferRequest)(nil),       // 1: pb.transfer.UpdateTransferRequest
	(*ApiResponseTransferDelete)(nil),   // 2: pb.transfer.ApiResponseTransferDelete
	(*ApiResponseTransferAll)(nil),      // 3: pb.transfer.ApiResponseTransferAll
	(*FindByIdTransferRequest)(nil),     // 4: pb.transfer.FindByIdTransferRequest
	(*emptypb.Empty)(nil),               // 5: google.protobuf.Empty
	(*ApiResponseTransfer)(nil),         // 6: pb.transfer.ApiResponseTransfer
	(*ApIResponseTransferDeleteAt)(nil), // 7: pb.transfer.ApIResponseTransferDeleteAt
}
var file_transfer_transfer_command_proto_depIdxs = []int32{
	0, // 0: pb.transfer.TransferCommandService.CreateTransfer:input_type -> pb.transfer.CreateTransferRequest
	1, // 1: pb.transfer.TransferCommandService.UpdateTransfer:input_type -> pb.transfer.UpdateTransferRequest
	4, // 2: pb.transfer.TransferCommandService.TrashedTransfer:input_type -> pb.transfer.FindByIdTransferRequest
	4, // 3: pb.transfer.TransferCommandService.RestoreTransfer:input_type -> pb.transfer.FindByIdTransferRequest
	4, // 4: pb.transfer.TransferCommandService.DeleteTransferPermanent:input_type -> pb.transfer.FindByIdTransferRequest
	5, // 5: pb.transfer.TransferCommandService.RestoreAllTransfer:input_type -> google.protobuf.Empty
	5, // 6: pb.transfer.TransferCommandService.DeleteAllTransferPermanent:input_type -> google.protobuf.Empty
	6, // 7: pb.transfer.TransferCommandService.CreateTransfer:output_type -> pb.transfer.ApiResponseTransfer
	6, // 8: pb.transfer.TransferCommandService.UpdateTransfer:output_type -> pb.transfer.ApiResponseTransfer
	7, // 9: pb.transfer.TransferCommandService.TrashedTransfer:output_type -> pb.transfer.ApIResponseTransferDeleteAt
	7, // 10: pb.transfer.TransferCommandService.RestoreTransfer:output_type -> pb.transfer.ApIResponseTransferDeleteAt
	2, // 11: pb.transfer.TransferCommandService.DeleteTransferPermanent:output_type -> pb.transfer.ApiResponseTransferDelete
	3, // 12: pb.transfer.TransferCommandService.RestoreAllTransfer:output_type -> pb.transfer.ApiResponseTransferAll
	3, // 13: pb.transfer.TransferCommandService.DeleteAllTransferPermanent:output_type -> pb.transfer.ApiResponseTransferAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transfer_transfer_command_proto_init() }
func file_transfer_transfer_command_proto_init() {
	if File_transfer_transfer_command_proto != nil {
		return
	}
	file_transfer_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_transfer_command_proto_rawDesc), len(file_transfer_transfer_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_transfer_command_proto_goTypes,
		DependencyIndexes: file_transfer_transfer_command_proto_depIdxs,
		MessageInfos:      file_transfer_transfer_command_proto_msgTypes,
	}.Build()
	File_transfer_transfer_command_proto = out.File
	file_transfer_transfer_command_proto_goTypes = nil
	file_transfer_transfer_command_proto_depIdxs = nil
}
