apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: payment-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Payment Gateway Go monolith project
  sourceRepos:
  - '*'
  destinations:
  - namespace: payment-gateway
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
